feat: 사용자 팔로우 기능 구현
numbble/backend pull request #16
Opened 2022-04-30 06:06 UTC by jaeesu

###  :speech_balloon: Motivation
* 본인을 팔로우 하려는 경우 에러를 발생시키는 부분을 service / domain 어디에 둬야 할지 고민하다가 Follow를 생성하는 곳의 책임이다. 라는 생각으로 domain 생성자 쪽에 두었습니다.

### :exclamation: Key changes
* 사용자 팔로우 기능
* 에러 발생
  * 없는 사용자를 팔로우 할 경우 
  * 이미 팔로우 한 사용자를 또 팔로우 할 경우
  * 본인을 팔로우 하는 경우

###  :pencil2: To Reviewers
* motivation에 적어둔 '본인을 팔로우 할 경우 에러 발생' 부분을 도메인에 두는 게 맞는 걸까요?
*  본인을 팔로우 할 경우 에러 발생, 부분에 대해 어떻게 서비스 테스트를 해야하는지 모르겠습니다.
  => 에러는 발생하지만, 그 에러가 발생한 것을 확인하고, 서비스 성공이 떠야 하는데 왜 아래 사진처럼 뜰까요?
  
<img width="600" alt="image" src="https://user-images.githubusercontent.com/50989437/166093791-9d0018d2-671c-42b3-b5cf-2e7811b75873.png">
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/50989437/166093822-36396945-7932-4b2f-bb47-615718bce912.png">

2022-04-30 06:50 UTC, ch0213 requested changes

2022-04-30 06:50 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/follow/domain/Follow.java
> +        if (fromMember.getId().equals(toMember.getId())) {
get을 통해 필드에 직접 접근하기보다는 `isEqualMember(Long id)` 같은 메서드를 만들어 객체에 직접 메시지를 전달하면 어떨까요?

2022-04-30 06:50 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/follow/ui/FollowController.java
> +        Member fromMember = memberRepository.findById(fromMemberId).orElseThrow(NotExistMemberException::new);
RequestParam을 직접 사용하는 것보다 요청을 받는 DTO를 만들면 어떨까요?
DTO를 만들면 validation을 할 때도 더 편할거같아요!

2022-04-30 07:00 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/follow/domain/Follow.java
> +        if (fromMember.getId().equals(toMember.getId())) {
넵 이 부분 수정해보겠습니다 ❗️

2022-04-30 07:02 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/follow/ui/FollowController.java
> +        Member fromMember = memberRepository.findById(fromMemberId).orElseThrow(NotExistMemberException::new);
@RequestParam("from_member") 이 부분은 현재 사용자의 아이디로 추후에 @LoginUser와 같이 현재 사용자를 불러 오는 것으로 바뀔 예정입니다!

2022-04-30 07:32 UTC, seongho-joo approved these changes
전에 팔로우기능을 만들때는 자기자신 팔로우는 생각도 못했었는데 이런 부분도 있었네요!
고생하셨습니다 !

2022-05-01 08:03 UTC, ch0213 approved these changes
고생하셨습니다!

2022-05-01 08:09 UTC, merged