feat: 소셜 로그인 기능 구현 (#12)
numbble/backend pull request #19
Opened 2022-05-01 12:44 UTC by ch0213

###  :speech_balloon: Motivation
* 카카오 소셜 로그인 기능 구현했습니다.

2022-05-01 14:48 UTC, jaeesu requested changes

2022-05-01 14:48 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/member/auth/infrastructure/KakaoClient.java
> +                    .getBody();
Kakao 응답 클래스 만들고, 그 클래스로 응답을 받아서 반환하면 반환 받은 곳에서도 objectmapper 사용하지 않고, getter로 쉽게 값을 가져올 수 있을 것 같습니다. ParameterizedTypeReference 참고해주세요!

2022-05-01 14:48 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/member/auth/util/LoginUser.java
> +}
@AuthenticationPrincipal를 포함하는 애노테이션(이전에 말씀드렸던 일반적으로 @CurrentUser로 사용하는 애노테이션)을 만들지 않으신 이유가 궁금합니다!

2022-05-01 14:48 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/common/config/SecurityConfig.java
> +                .anyRequest().authenticated();
role에 따라 url 분리해서 인가 테스트 해 주실 수 있을까요?

2022-05-01 14:48 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/member/auth/application/membercreator/MemberCreatorFactory.java
> +                .filter(provider -> provider.getProviderName().equals(providerName))
oauthProvider의 수가 많지 않아서 성능에는 큰 차이가 없겠지만, filter 대신 takeWhile을 사용할 수 있을 것 같습니다

2022-05-01 14:48 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/member/auth/application/membercreator/MemberCreatorFactory.java
> +    private OauthProvider findMatchProvider(String providerName) {
OauthClientFactory랑 함수가 중복되는데, OauthProvider에 static 메서드를 만들면 좋을 것 같습니다. OauthProvider 내부에서 valueOf를 사용하고 예외처리 해도 될 것 같아요

2022-05-01 14:48 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/member/auth/util/JwtTokenArgumentResolver.java
> +public class JwtTokenArgumentResolver implements HandlerMethodArgumentResolver {
이 함수로 인해 @LoginUser 애노테이션이 작동할 수 있는 것 같은데 컨트롤러에서 애노테이션을 호출하면, resolveArgument를 통해 자동으로 값을 할당해주는 방식이 맞나요?
resolver를 config에 넣어준 곳이 없는 것 같은데 어떻게 LoginUser가 resolver를 찾아서 동작할 수 있는 건지 궁금합니다!

2022-05-02 05:44 UTC, seongho-joo reviewed
env 파일 slack에서 공유해주세요!

2022-05-02 05:46 UTC, seongho-joo commented
**Controller**에서 로그인한 유저를 어떻게 받아오는지 알 수 있을까요?

2022-05-04 08:55 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/member/auth/infrastructure/KakaoClient.java
> +public class KakaoClient implements OauthClient {
말씀해주셔서 OAuth2 Client에 대해 알아봤는데 정말 편리한 기능이 많네요. 일단은 직접 구현하고 이후에 프로젝트 핵심 기능 구현 마무리하면 적용해보겠습니다!

2022-05-04 09:01 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/member/auth/util/JwtTokenProvider.java
> +        return Long.valueOf(Jwts.parser().setSigningKey(REFRESH_KEY)
이 부분은 처음에 구현할 때 고민을 많이 했는데, Enum을 사용한다면 결국 secret key에 대한 getter를 생성해야 하고 그렇다면 프로젝트 어디에서나 getter를 통해 조회할 수 있기 때문에 보안상 좋지 않다고 생각했습니다 (setter를 사용하지 않는 것과 비슷한 이유). getter 생성하지 않고 구분용으로 쓴다면 코드 양은 줄지 않을 것 같았으며 각 메서드가 아예 다른 클래스에서 사용되므로 다른 메서드로 분리하여 알아보기 쉽게 하는게 더 좋다고 생각했습니다!

2022-05-04 09:27 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/member/auth/application/membercreator/MemberCreatorFactory.java
> +    private OauthProvider findMatchProvider(String providerName) {
좋은 의견 감사합니다!

2022-05-04 09:37 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/member/auth/infrastructure/KakaoClient.java
> +                    .getBody();
이 부분도 이후에 핵심 기능 구현 완료 후 적용해보겠습니다!

2022-05-04 09:37 UTC, ch0213 commented
> env 파일 slack에서 공유해주세요!

네 알겠습니다 ~

2022-05-04 09:38 UTC, ch0213 commented
> **Controller**에서 로그인한 유저를 어떻게 받아오는지 알 수 있을까요?

@LoginUser 어노테이션을 통해 사용할 수 있습니다. 수정 사항 반영해서 다시 올리겠습니다!

2022-05-04 10:09 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/common/config/SecurityConfig.java
> +                .anyRequest().authenticated();
이와 유사한 url별 접근 테스트를 이 전에(#9) 작성했다가 테스트를 위한 url이 따로 필요해서 프로덕션 코드가 지저분해진다고 생각해 삭제했습니다. 이후에 인수 테스트에서 같이 진행하는건 어떻게 생각하시나요?

2022-05-04 14:47 UTC, seongho-joo approved these changes
고생하셨습니다!

2022-05-04 14:53 UTC, jaeesu approved these changes

2022-05-05 02:02 UTC, merged

2022-05-05 02:51 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/common/config/SecurityConfig.java
> +                .anyRequest().authenticated();
이 부분은 role에 따라서 확인하셨다면 상관없습니다!
혹시나 확인하는 걸 깜빡해서 제대로 동작 안 하는 상황을 대비하기 위해서 부탁던거라 상관없습니다~