feat: 영상 수정 기능 구현
numbble/backend pull request #21
Opened 2022-05-02 08:07 UTC by seongho-joo

###  :speech_balloon: Motivation
* repository 조회 및 수정 테스트를 먼저 진행한 후 수정 기능 개발을 시작했습니다.

### :exclamation: Key changes
* 영상 수정 기능 구현
* 등록 서비스를 개발할 때 `@Transactional `을 작성하지 않아서 추가했습니다.
* 예외 처리
  * 로그인이 안되어 있을 경우
  * 작성자가 아닌 다른 유저가 수정을 시도했을 경우
  * 영상이 존재하지 않을 경우

###  :pencil2: To Reviewers
* 권한이 없는 사용자가 수정을 시도했을 때 발생하는 예외 테스트를 작성했으나 status가 200이 나와 실패 케이스는 제외하고 올렸습니다. 😅
* 예외 처리가 더 필요한 부분이 생각나시면 말씀해주세요!

2022-05-02 15:08 UTC, seongho-joo commented
rebase를 했더니 커밋 로그가 지저분해진 것 같네요😅

2022-05-03 03:55 UTC, jaeesu commented
제가 rebase를 이번에 처음 알아서 용도를 잘 모르겠는데, 혹시 rebase를 왜 하신 건가요?

2022-05-03 04:25 UTC, seongho-joo commented
> 제가 rebase를 이번에 처음 알아서 용도를 잘 모르겠는데, 혹시 rebase를 왜 하신 건가요?

![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FcofZo0%2FbtqBkOJybm6%2FRshCv0OqsydpuNCRPcIxu1%2Fimg.png)
위 사진과 같이 Git History가 깔끔해진다는 것을 보고 한번 시도해봤습니다!

2022-05-03 08:57 UTC, jaeesu requested changes

2022-05-03 08:57 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +    public CommonResponse<VideoResponse> saveVideo(@ModelAttribute VideoRequest videoRequest,
영상 저장, 수정 시에 반환값으로 영상 정보(videoResponse)를 반환하는 이유가 있나요?

2022-05-03 08:57 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/ui/VideoControllerTest.java
> +    @DisplayName("video 수정 - 성공")
validation이나 존재하지 않는 영상에 대한 실패 테스트도 있으면 좋을 것 같습니다!

2022-05-03 08:57 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
>          this.viewCount = viewCount;
수정 상황을 위해 엔티티에 @DynamicUpdate 달아줘도 좋을 것 같아요

2022-05-03 08:57 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/dto/VideoUpdateRequest.java
> +    private String category;
valid 조건 달고 postman 확인까지 해주세요~

2022-05-03 08:57 UTC, jaeesu commented on src/main/resources/init.sql
>  CREATE TABLE video
base time entity 추가해주세요

2022-05-03 08:57 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/application/VideoServiceTest.java
> -            "https://d659rm6fgd091.cloudfront.net/test.mov");
@Nested 사용해서 저장, 조회, 수정 등을 묶어서 관리하면 어떨까요?

2022-05-03 08:57 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/application/VideoServiceTest.java
> +    @DisplayName("video 수정 - 실패, 저장한 영상이 존재하지 않을 경우")
DisplayName이 저장한 영상이 사라졌다는 의미로 보여서 "존재하지 않는 영상을 수정하려는 경우"로 바꾸면 어떨까요?

2022-05-03 08:57 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/common/exception/ExceptionType.java
> +    NOT_AUTHOR_EXCEPTION("작성자가 아니므로 권한이 없습니다.",UNAUTHORIZED, NotAuthorException.class);
에러 메시지에 "접근 권한"이 없습니다.로 수정하면 좋을 것 같아요.
아니면 작성자만 접근할 수 있다는 식으로 바꿔도 좋을 것 같아요.
어떤 권한인지 명시를 해 줘야지 깔끔할 것 같은데, 저희는 작성자가 아닌 모든 상황을 통틀어서 사용할 것이니 "접근"으로 묶으면 될 것 같습니다

2022-05-03 08:57 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/dto/VideoRequest.java
>  public class VideoRequest {
이 부분은 이전에 체크했어야 했는데, 못 봤네요..ㅎㅎ
여기도 valid 조건 달고 마지막 확인까지 해주세요~

2022-05-03 08:57 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/domain/VideoRepositoryTest.java
>  import org.junit.jupiter.api.Test;
jpa테스트하실 때 @AutoConfigureTestDatabase(replace = NONE) 달아주세요!
jpa 테스트 기본값이 임베디드 디비 돌아가게 하는거라서 제가 local.yml에 설정한 디비를 사용할 수가 없어요

2022-05-03 08:57 UTC, jaeesu commented
인수테스트랑 통합테스트는 나중에 작성하려고 하신건가요?

2022-05-03 09:58 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +    public CommonResponse<VideoResponse> saveVideo(@ModelAttribute VideoRequest videoRequest,
영상 저장, 수정 후에  id값을 넘겨서 현재 저장, 수정한 영상 조회를 프론트쪽에서 바로 조회 api를 호출할 수 있게 videoResponse로 반환을 했는데 CommonResponse<Long> 으로 반환해도 상관없으면 그렇게 수정 하겠습니다!

2022-05-03 10:00 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/video/ui/VideoControllerTest.java
> +    @DisplayName("video 수정 - 성공")
postman에서 validation 테스트를 해본 결과 정상적으로 401을 반환하는데 테스트 코드에서는 수정 성공으로 인해 올리지 않았습니다. 
존재하지 않는 영상 테스트는 추가하도록 하겠습니다.

2022-05-03 10:02 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
>          this.viewCount = viewCount;
@DynamicUpdate는 처음 들어보는데 어떤 애노테이션인지 알아본 후 추가하도록 하겠습니다.

2022-05-03 10:02 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/dto/VideoUpdateRequest.java
> +    private String category;
controller 에서 valid를 다는 것과 dto에 valid 다는 것과 차이점이 있나요?

2022-05-03 10:03 UTC, seongho-joo commented on src/main/resources/init.sql
>  CREATE TABLE video
네 추가해놓겠습니다!

2022-05-03 10:03 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/ui/VideoControllerTest.java
> +    @DisplayName("video 수정 - 성공")
제가 의도한 validation은 requestDto에 대한 것이었습니다!
예를 들어 description이 필수값인데, dto에 null로 들어왔다면 에러를 발생시켜야 되는 상황이요

2022-05-03 10:05 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/dto/VideoUpdateRequest.java
> +    private String category;
controller에 valid를 다른 것은 해당 클래스에 달린 제약조건을 확인하라는 의미입니다. videoUpdateRequest에 not null, length 같은 조건을 달아줘야 controller가 어떤 제약 조건을 확인해야 하는지 알 수 있으니까요!
현재 상황에서는 controller가 videoUpdateRequest에서 확인할 수 있는 제약조건이 없습니다

2022-05-03 10:05 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/video/ui/VideoControllerTest.java
> +    @DisplayName("video 수정 - 성공")
title 값은 널이 되면 안되니 추가해놓겠습니다!

2022-05-03 10:06 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/dto/VideoUpdateRequest.java
> +    private String category;
아 알겠습니다! 추가 해놓겠습니다!

2022-05-03 10:07 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/video/application/VideoServiceTest.java
> -            "https://d659rm6fgd091.cloudfront.net/test.mov");
@nested도 한번 알아본 후에 추가하도록 하겠습니다.

2022-05-03 10:07 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/video/application/VideoServiceTest.java
> +    @DisplayName("video 수정 - 실패, 저장한 영상이 존재하지 않을 경우")
아 워딩이 조금 이상하게 느껴지긴 하네요 수정하겠습니다~

2022-05-03 10:10 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/dto/VideoUpdateRequest.java
> +    private String category;
category, description은 null이 허용되나요?

2022-05-03 10:16 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/dto/VideoUpdateRequest.java
> +    private String category;
category는 아직 엔티티 구현이 안되어서 null 값을 허용하게 만들어뒀는데 description은 회의했을 때 회원이 작성할 수도 있고 작성안할 수도 있다는 걸로 알고 있어서 null이 허용되게 했습니다.

2022-05-03 10:25 UTC, seongho-joo commented
> 인수테스트랑 통합테스트는 나중에 작성하려고 하신건가요?

https://zereight.tistory.com/545
위 링크에 인수테스트를 보면 실환경에서 테스트한다고 나와있어서 모든 개발이 끝난 후에 테스트 시나리오를 작성 후 테스트하려고했습니다! 

통합 테스트는 비디오 기능 구현을 완료 후 작성하려고 작성하지 않았습니다.

2022-05-03 10:26 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/video/domain/VideoRepositoryTest.java
>  import org.junit.jupiter.api.Test;
아 그렇군요! 추가하도록 하겠습니다

2022-05-03 12:04 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/dto/VideoUpdateRequest.java
> +    private String category;
넵 알겠습니다!

2022-05-03 16:19 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/video/ui/VideoControllerTest.java
> +    @DisplayName("video 수정 - 성공")
`any()`를 사용할 때 `.class`를 넣어줘야하는지 모르고 해서 이때까지 테스트가 제대로 작동하지 않은 것 같습니다!! 
`any(VideoUpdateRequest.class)`를 넣고 하니깐 접근 권한 테스트도 성공하네요

2022-05-04 01:56 UTC, jaeesu commented
> > 인수테스트랑 통합테스트는 나중에 작성하려고 하신건가요?
> 
> https://zereight.tistory.com/545 위 링크에 인수테스트를 보면 실환경에서 테스트한다고 나와있어서 모든 개발이 끝난 후에 테스트 시나리오를 작성 후 테스트하려고했습니다!
> 
> 통합 테스트는 비디오 기능 구현을 완료 후 작성하려고 작성하지 않았습니다.

제가 인수테스트에 대해서 제대로 모르는 상태였네요...ㅠ 저는 통합테스트는 기능 단위로 작성하는 게 좋다고 생각했는데, 이 부분도 일반적인 방법을 잘 모르겠어서 한 번 상의 해보면 좋을 것 같습니다!

2022-05-04 03:07 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/dto/VideoRequest.java
> +    @NonNull
이 클래스에는 @valid 애노테이션을 안 달아주셔도 됩니다!

혹시 postman으로 title이 없을 때 제대로 에러가 발생하는지 확인하셨나요?
지금 사용하신 @NonNull은 롬복 애노테이션이고 valid는 javax.validation 패키지의 애노테이션이라서 같이 작동하는지 궁금합니다!

2022-05-04 06:49 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/dto/VideoRequest.java
> +    @NonNull
**@NonNull**을 내가 잘못 추가했었네요! 
**@NotEmpty**로 추가하고 테스트한 결과 에러가 제대로 발생하는거 확인했습니다

2022-05-04 08:22 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/dto/VideoUpdateRequest.java
> +    private String category;
NotEmpty는 공백(" ")은 허용하는 걸로 알고 있어요. NotBlank도 고려해봐주세요~

2022-05-04 08:29 UTC, jaeesu requested changes

2022-05-04 08:29 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
>          this.member = member;
메서드명 맞게 작성하신게 맞나요..?

2022-05-05 02:35 UTC, ch0213 requested changes

2022-05-05 06:03 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void update(Video video) {
파라미터로 DTO를 받게 수정하겠습니다!

2022-05-05 06:06 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        validateAuthor(member, video);
`video.update()` 로직안에 권한 검증하는 코드를 추가하라는 말씀인가요?

2022-05-05 06:06 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/dto/VideoResponse.java
> +    public static VideoResponse of(Video video) {
네 참고해서 수정하겠습니다!

2022-05-05 06:13 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void update(Video video) {
도메인 로직에서 Dto를 받는건 지양하는게 좋을 것 같습니다!
`public void update(String title, String description)` 이렇게 하는게 더 좋을 것 같아요.

2022-05-05 06:16 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +    private Video findVideo(Long videoId) {
멤버 찾는 코드가 중복이 돼서 메서드를 따로 빼서 사용을 했는데 매개변수로 Member 객체로 받아서 멤버찾는 로직 없이 사용해도 될 것 같네요!

2022-05-05 06:21 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/dto/VideoUpdateRequest.java
> +@Builder
dto 테스트할 때 builder쓰는 부분이 있어서 없으면 에러가 발생할 것 같아요

2022-05-05 06:31 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        validateAuthor(member, video);
이미 Video와 Member는 연관관계가 있어서 그렇게 하는게 더 좋을 것 같아요.
그리고 Video의 상태값을 변경하는 기능이니까 Validation 로직이 Service Layer에 있는 것보다 Video에 있는게 더 적절하게 책임을 분리하는 것 같습니다.

2022-05-05 06:39 UTC, ch0213 requested changes

2022-05-05 06:39 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        saveVideo.addVideoToMember(member);
Video가 연관관계의 주인이기 때문에 이 부분은 없어도 될 것 같아요 😄

2022-05-05 06:39 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void addVideoToMember(Member member) {
getter로 Member의 필드에 직접 접근하는 것은 디미터 법칙을 위반합니다! member에 `saveNewVideo(Video video)`와 같이 메서드를 만든 후 `member.saveNewVideo(video)` 처럼 video은 책임을 위임해주는 역할만 하면 될 것 같아요. 추가로 멤버에 List<Video>가 있다면 일급 컬렉션으로 관리해도 좋을 것 같네요 👍

2022-05-05 06:41 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +        Member loggedInMember) throws IOException {
그렇네요 ! 유지보수할 때 고치는게 좋을까요? 아니면 지금 바로 고치는게 좋을까요?

2022-05-05 06:42 UTC, jaeesu requested changes

2022-05-05 06:42 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +        return this.member.equals(member);
Member 클래스의 isEqualMember를 사용하는 것도 좋을 것 같습니다!
member의 동일성을 비교하는 것도 member의 책임인 것 같다는 생각도 듭니다

2022-05-05 06:46 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/dto/VideoUpdateRequest.java
> +@Builder
Builder가 여러 생성자 만들기가 곤란할 때 편의성 측면에서 많이 사용한다고 생각을 하는데, VideoUpdateRequest 외부에서 생성할 일이 없으니, 굳이 Builder를 사용하지 않고, 생성자를 이용해도 될 것 같습니다

2022-05-05 06:50 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/dto/VideoUpdateRequest.java
> +@Builder
아 넵 그럼 생성자를 이용해서 테스트를 진행해도 되겠네요 수정하겠습니다

2022-05-05 06:51 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +        Member loggedInMember) throws IOException {
저 부분을 확인해봤는데, amazonS3Uploader로부터 발생한 예외가 service를 거쳐 controller까지 올라오더라구요.
저 해당 클래스에서 예외를 잡도록 처리하면 좋을 것 같습니다!

2022-05-05 06:56 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +        return this.member.equals(member);
좋은 생각입니다!

2022-05-05 07:26 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void update(Video video) {
아 네 알겠습니다 !

2022-05-05 07:44 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +        if (!isAuthorOf(member)) {
Author체크를 update의 최상단에 두어 Author가 아니라면 값을 수정하기 전에 에러를 발생시키는게 맞는 순서인 것 같습니다.

2022-05-05 13:23 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +        if (!isAuthorOf(member)) {
이 부분은 영상에 연관된 멤버가 현재 사용자가 맞는지 확인하는 부분인 것 같습니다 
a 사용자에게 b 사용자가 올린 영상을 수정할 권한을 주지 않기 위해서 체크하는 것이요!

2022-05-05 13:52 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +        if (!isAuthorOf(member)) {
혹시 모를 상황도 대비하는게 좋다고 생각해서 이 검증은 있어야된다고 생각합니다

2022-05-05 16:45 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +        if (!isAuthorOf(member)) {
저는 Objects.nonNull을 보고 말씀드린건데 지워진 코드였군요! 착각했네요 ㅎㅎ

2022-05-05 16:48 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void addVideoToMember(Member member) {
일급 컬렉션은 좀 더 알아본 후에 적용하도록 하겠습니다!

2022-05-06 02:30 UTC, jaeesu approved these changes

2022-05-06 08:47 UTC, ch0213 approved these changes
고생하셨습니다!

2022-05-06 08:47 UTC, merged