feat: 사용자 팔로우 취소 기능 구현
numbble/backend pull request #23
Opened 2022-05-03 09:18 UTC by jaeesu

###  :speech_balloon: Motivation
* 팔로우 요청 기능과 크게 다를 것 없이 구현했습니다.

### :exclamation: Key changes
* 팔로우 취소 api 추가
* 에러 상황
  * 존재하지 않는 사용자에 대해 팔로우 취소를 요청
  * 팔로우되어 있지 않는 사용자에 대해 팔로우 취소를 요청
    (본인을 팔로우 취소하는 경우도 포함)
    (애초에 본인을 팔로우하는 경우는 존재할 수 없으므로 "본인은 팔로우 취소할 수 없습니다" 이 경우를 따로 빼지 않았음.)

###  :pencil2: To Reviewers
* 통합테스트와 인수테스트는 제 생각대로 작성해봤습니다. 인수테스트 시나리오는 누군가에게 설명해준다고 생각하고 작성해봤는데, 이런 식으로 하는게 맞는지 잘 모르겠네요ㅎㅎ 😢

2022-05-04 07:12 UTC, seongho-joo requested changes

2022-05-04 07:12 UTC, seongho-joo commented on src/main/resources/application-test.yml
> +      schema-locations: classpath:init.sql
mode는 어떤 의미인가요?

2022-05-04 07:12 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/follow/acceptance/FollowAcceptanceScenario.md
> +        "user1"은 "user2"를 팔로우하고 있지 않기 때문에, 팔로우하지 않은 사용자라는 메시지와 함께 에러가 발생한다.
이렇게 시나리오를 작성해서 올리는 것도 나쁘지않은 것 같네요

2022-05-04 07:12 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/follow/acceptance/FollowingBaseAcceptanceTest.java
> +}
인수 테스트랑 통합 테스트를 나눠서 테스트를  나누신 이유가 있나요?

2022-05-04 08:19 UTC, jaeesu commented on src/main/resources/application-test.yml
> +      schema-locations: classpath:init.sql
sql.init.mode : alway로 두면 항상 schema-locations의 sql문을 이용해 데이터베이스를 초기화한다는 의미입니다. ddl-auto에서 schema를 추가했다고 보시면 됩니다!

jpa.defer-datasource-initialization: true랑 어떤 연관이 있는지는 잘 모르겠으나, 이 부분까지 적어줘야 정상적으로 초기화가 되어 같이 적어줬습니다.

2022-05-04 08:20 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/follow/acceptance/FollowingBaseAcceptanceTest.java
> +}
인수 테스트랑 통합 테스트는 테스트 방법도 다르고, 목적도 다르기 때문에 따로 작성해야 한다고 생각했습니다.
또 인수 테스트는 시나리오대로 작성하고, 그 시나리오만 확인할 수 있도록 격리해야 한다는 것도 본 적이 있습니다!

2022-05-04 14:51 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/follow/acceptance/FollowingBaseAcceptanceTest.java
> +}
혹시 어디서 참고했는지 알 수 있을까요?!

2022-05-04 14:52 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/follow/acceptance/FollowingBaseAcceptanceTest.java
> +}
이것저것 구글링하다 본거라 따로 저장해놓진 않았네요ㅠ 인수테스트 격리 정도로 치면 많이 나올 것 같습니다

2022-05-05 02:34 UTC, ch0213 requested changes

2022-05-05 02:42 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/follow/application/FollowService.java
> +
id null 체크를 위해 delete 대신 deleteById를 사용하고 싶어서 저렇게 짰었습니다.
근데 어차피 위에서 exists 하면서 값을 조회하고 되고, 값이 있다면 id가 null이 아니라는 것이 보장되는 거네요!
수정해보겠습니다!

2022-05-05 02:42 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/follow/ui/FollowController.java
> +        Member fromMember = memberRepository.findById(fromMemberId).orElseThrow(NotExistMemberException::new);
@LoginUser로 Member를 받아올 수 있으니, 이제 이 부분은 아예 빼고 될 것 같습니다!
이 부분 다 수정하고 로그인 부분 코드랑 머지되면 그때 수정하도록 하겠습니다

2022-05-05 02:45 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/follow/application/FollowService.java
> +
아 삭제할 때 사용자 아이디 말고, 팔로우 아이디를 받아서 해도 된다고 하신 건가보네요!
간단한데 왜 생각을 못 했는지...ㅎㅎ 수정하겠습니다~

2022-05-05 02:59 UTC, ch0213 approved these changes
고생하셨습니다!

2022-05-05 09:15 UTC, merged