feat: 영상 삭제 기능 구현
numbble/backend pull request #26
Opened 2022-05-06 08:25 UTC by seongho-joo

###  :speech_balloon: Motivation
* repository 삭제 테스트를 먼저 진행한 후 삭제 기능 개발을 시작했습니다.

### :exclamation: Key changes
* 영상 삭제 기능 구현
* Repository 테스트 중 연관관계 매핑 테스트 추가했습니다.
* 예외처리는 수정 기능과 똑같이 처리했습니다.

###  :pencil2: To Reviewers
* @LoginUser를 활용해서 테스트를 하려고했는데 어떻게 해야할지 몰라서 회원 id를 쿼리스트링으로 넘겨 테스트하는 방법으로 진행했습니다.

2022-05-06 09:17 UTC, jaeesu commented
브랜치를 나누는 것이 문제 상황이 발생했을 때, 롤백하려는 의도도 있다고 생각합니다.
커밋이 계속 합쳐지고 있는데, 브랜치별로 독립적으로 다룰 수 있도록 합쳐지지 않았으면 좋겠습니다.

2022-05-06 12:46 UTC, jaeesu requested changes

2022-05-06 12:46 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +    private Video findVideo(Long videoId) {
이전 pr에서 findMember와 같은 이유로 굳이 함수로 분리하지 않아도 될 것 같습니다.
findById가 중복되기는 하지만, 충분히 그 의도를 파악할 수 있고 findVideo 또한 중복되니까요!

2022-05-06 12:46 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/ui/VideoControllerTest.java
> +
정말 필요한 경우가 아니면 mock 테스트는 하지 않기로 했던 거 아닌가요..?

2022-05-06 12:49 UTC, seongho-joo commented
> 브랜치를 나누는 것이 문제 상황이 발생했을 때, 롤백하려는 의도도 있다고 생각합니다.
> 커밋이 계속 합쳐지고 있는데, 브랜치별로 독립적으로 다룰 수 있도록 합쳐지지 않았으면 좋겠습니다.
> 이전의 커밋들이 합쳐지니 코드 리뷰할 때, 수정사항이 많아 코드 보기도 힘들어지네요 😢

저건 그냥 merge만 진행했는데.. 저게 왜 저렇게 뜬지 모르겠네요 ㅠ

2022-05-06 12:51 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +    private Video findVideo(Long videoId) {
아 네! 알겠습니다!

2022-05-06 12:54 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/video/ui/VideoControllerTest.java
> +
이전에 테스트 진행했던건 마무리 해야되겠다 해서 작성했는데 조회를 만든 후 통합 테스트 만들고 지울 생각이었습니다! 
지우지는 말까요?

2022-05-06 17:05 UTC, jaeesu requested changes

2022-05-07 10:44 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/video/ui/VideoControllerTest.java
> +
정처기를 공부할 때 통합 테스트 전략 중 빅뱅 통합 전략이 기억나서 모든 기능을 만든 후 통합하면서 작성하려고 했습니다! 각 기능마다 통합테스트를 만들어서 추가하는게 더 좋을까요?

2022-05-07 10:47 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/video/domain/VideoRepositoryTest.java
> +
아 ! 아무 생각없이 작성하다가 dto를 넣었네요! 수정하겠습니다!

2022-05-07 12:21 UTC, jaeesu commented
> > 브랜치를 나누는 것이 문제 상황이 발생했을 때, 롤백하려는 의도도 있다고 생각합니다.
> > 커밋이 계속 합쳐지고 있는데, 브랜치별로 독립적으로 다룰 수 있도록 합쳐지지 않았으면 좋겠습니다.
> > 이전의 커밋들이 합쳐지니 코드 리뷰할 때, 수정사항이 많아 코드 보기도 힘들어지네요 😢
> 
> 저건 그냥 merge만 진행했는데.. 저게 왜 저렇게 뜬지 모르겠네요 ㅠ

아..그렇군요..! ㅠㅠㅠ 알겠습니다!

2022-05-07 12:38 UTC, ch0213 requested changes

2022-05-07 12:38 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        Video findVideo = videoRepository.findById(videoId).orElseThrow(NotExistVideoException::new);
orElseThrow에 개행 있으면 좋을거같아요!

2022-05-07 12:38 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        loggedMember.removeVideo(findVideo);
Video 삭제는 member 말고 Video에서 하는게 좋을거 같습니다.
그리고 member의 remove 메서드를 봤는데 연관관계의 주인이 아니라 member에서 지우는건 의미가 없어보여요!
현재 member가 video에 권한이 있는지만 체크하고 videoRepository.delete()로 지우면 될 것 같습니다 ㅎㅎ

2022-05-07 12:38 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void addVideoToMember(Member member) {
연관관계를 다시 살펴봤는데 이 부분은 필요 없지 않을까요?? 아마 video에서 추가하면 Member에도 자동으로 추가될거에요

2022-05-07 12:38 UTC, ch0213 commented on src/test/java/numble/team4/shortformserver/video/domain/VideoRepositoryTest.java
> +    //== video 조희 ==//
DisplayName에서 이미 충분히 의도를 알 수 있어서 주석은 제거해도 좋을 것 같습니다!

2022-05-07 12:38 UTC, ch0213 commented on src/test/java/numble/team4/shortformserver/video/domain/VideoRepositoryTest.java
> +        assertThrows(NotExistVideoException.class,
orElseThrow에 개행 있으면 좋을것같아요~

2022-05-07 12:45 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void addVideoToMember(Member member) {
김영한님 강의를 들었을 때 연관관계 메서드가 필요하다고해서 넣긴했는데 테스트할 때 flush, clear를 한 후 연관관계 테스트를 하면 될까요?

2022-05-07 12:49 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        loggedMember.removeVideo(findVideo);
비디오 도메인에 검증 메서드를 추가 후 밑에 코드 처럼 사용하는게 좋을까요?
```java
//Service

findVideo.validateAuthor(loggedMember);

// Domain
 public void update(String title, String description, Member member) {
        validateAuthor(member);

        this.title = title;
        this.description = description;
    }

    public void validateAuthor(Member member) {
        if (!this.member.equals(member)) {
            throw new NotAuthorException();
        }
    }
```

2022-05-07 12:50 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void addVideoToMember(Member member) {
연관관계 편의 메서드는 연관관계의 주인이 아닌 곳에서 추가할 때 필요하다고 하셨을거에요.
예를 들어, Team과 Member가 있을 때 보통 N인 쪽이 연관관계의 주인이어서 Member를 주인으로 합니다.
이럴 경우에 Team에서 member를 추가해도 연관관계의 주인이 아니기 때문에 반영이 되지 않거든요ㅎㅎ
그럴 경우에는 team에서 member를 추가하면 member에 연관관계 메서드를 추가해주는데 이런 상황에서는 필요 없을겁니다 😄

2022-05-07 12:51 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/video/domain/VideoRepositoryTest.java
> +    //== video 조희 ==//
이 부분은 조회 기능을 만들면서 제거를 해놨습니다!

2022-05-07 12:53 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void addVideoToMember(Member member) {
`addVideoToMember`를 제거하면 `saveNewVideo`는 어디서 호출하는게 좋을까요?

2022-05-07 12:54 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        loggedMember.removeVideo(findVideo);
네 검증만 한 후 `videoRepository.delete(video)` 처럼하면 될 것 같습니다 ㅎㅎ

2022-05-07 12:54 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void addVideoToMember(Member member) {
제거해도 될 것 같습니다

2022-05-07 13:06 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void addVideoToMember(Member member) {
이 메서드를 제거해도 기능은 똑같이 하지만, 객체의 입장에서 봤을 때, member와 video 양쪽에 모두 참조값을 줘야 한다고 생각합니다. 그래서 이 메서드를 그대로 두고(메서드명은 addToMember로 수정) videoRequest의 tovideo를 아래와 같이 고치면 어떨까 합니다!
```java
public Video toVideo(String videoUrl, String thumbnailUrl, Member member) {
        Video video = Video.builder()
            .title(title)
            .description(description)
            .videoUrl(videoUrl)
            .thumbnailUrl(thumbnailUrl)
            .likeCount(0L)
            .viewCount(0L)
            .build();
        video.addToMember(member);
        return video;
    }
```

저도 원래는 toVideo 내에서 연관관계 설정을 다 해줬었는데, 최대한 도메인 내부에서 연관관계를 설정할 수 있도록 하는 게 좋을 것 같습니다.
다들 어떻게 생각하시나요?

2022-05-07 16:45 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void addVideoToMember(Member member) {
저도 객체 입장에서 봤을 때, 연관관계 편의 메서드는 있는게 좋다고 생각합니다. 충환님은 어떻게 생각하시나요?

2022-05-08 17:51 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/ui/VideoControllerTest.java
> +
지금 당장 빅뱅 통합 전략에 대해 확실히 이해하진 못 해서 통합테스트에 대한 생각을 말씀드리자면, 통합테스트의 목적은 어떤 기능에 있어서 repository, service, controller가 잘 통합해서 작동하느냐를 테스트하는 것이라고 알고 있습니다.
그래서 굳이 등록, 취소, 수정 등이 완성된 후가 아니라, 등록에 대한 repository, service, controller가 잘 통합하는지 테스트를 즉각적으로 하는 것도 통합테스트의 목적에 부합한다고 생각합니다!

mock 테스트는 크게 의미가 없는 것 같다고 저희끼리 의견이 모아졌으니, 통합테스트를 바로 작성하시는 게 좋을 것 같습니다. 부분적으로 mock을 이용해서 코드를 세세하게 확인해야 하는 부분에는 mock을 사용해도 좋으나, 통합테스트로 끝낼 수 있는 부분은 굳이 작성하지 않아도 될 것 같아요 😄

2022-05-09 04:00 UTC, jaeesu approved these changes

2022-05-09 06:05 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void addVideoToMember(Member member) {
생각을 해보니 나의 프로필에서 내가 올린 영상들을 볼 수 있어야하니깐 연관관계 메서드가 있어야하지 않을까요?

2022-05-09 12:27 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void addVideoToMember(Member member) {
어떤 연관관계 메서드를 말씀하시는 건가요? addVideoToMember와는 별개의 메서드를 말씀하시는 건가요?

2022-05-09 12:28 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void addVideoToMember(Member member) {
별개의 메서드는 아니고 `addToMember`와 `saveNewVideo`, `removeVideo` 메서드를 말하는 겁니당

2022-05-09 13:38 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void addVideoToMember(Member member) {
네 필요하신 건 자유롭게 추가하시면 될 것 같아요~

2022-05-10 04:57 UTC, ch0213 approved these changes
고생하셨습니다!

2022-05-10 05:10 UTC, merged