Feature/follow #24
numbble/backend pull request #28
Opened 2022-05-07 12:17 UTC by jaeesu

###  :speech_balloon: Motivation
* response를 가져올 때, 필요없는 데이터의 조회를 조금이라도 줄이고자 QueryProjection을 사용했습니다.
* 

### :exclamation: Key changes
* 팔로우(팔로잉, 팔로워) 목록 조회 api 추가
* 예외 사항
  * 존재하지 않는 사용자의 팔로우, 팔로워 목록 조회 요청 

###  :pencil2: To Reviewers
* reviewer들에게 전하고 싶은 말이 있다면 적어주세요.

2022-05-08 07:17 UTC, seongho-joo requested changes

2022-05-08 07:17 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/follow/infrastructure/FollowCustomRepositoryImpl.java
> +
제가 아직 QueryDSL을 써보지 않아서 그런데 앞에 Q 붙은게 QueryDSL을 사용해서 생기는게 맞죠?

2022-05-08 07:17 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/follow/ui/dto/FollowResponse.java
> +public class FollowResponse {
Lombok에 대해서 찾아볼 때 `@Data`는 사용하지않는게 좋다고 봤는데 dto라 상관없어서 사용하신건가요?

2022-05-08 07:39 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/common/config/SecurityConfig.java
> +                .antMatchers(HttpMethod.GET,"/v1/users/following/from", "/v1/users/following/to").permitAll()
/** 으로 처리하지 않는 이유를 여쭤보시는 거라면, get 방식의 /{toUserId}가 있기 때문에 처리할 수 없었습니다.
추가적으로 문자열에 대한 정규 표현식으로 나타내보려고 했지만, toUserId의 id가 string으로도 받아지기 때문에 적용하지 못 했습니다.
지금 나중에 /toUserId}부분을 숫자에 대한 정규 표현식으로 나타낼 수 있는지 찾아보고 적용해 불 예정입니다.

2022-05-08 07:40 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/follow/infrastructure/FollowCustomRepository.java
> +}
프론트와 상의 후 한 번에 반환하는 걸로 했습니다

2022-05-08 07:41 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/follow/infrastructure/FollowCustomRepositoryImpl.java
> +
QueryDSL을 사용하면 Follow 도메인과는 또 따로 QFollow라는 클래스가 생깁니다.
jpaqueryfactory를 사용하는 문법에서 사용할 수 있도록 생기는 클래스입니다. build할 때마다 build 폴더에 생겨요!

2022-05-08 07:43 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/follow/ui/dto/FollowResponse.java
> +public class FollowResponse {
넵! 이게 전체인지는 기억이 잘 안나지만, @Data에는 다음의 애노테이션이 포함됩니다. @setter, @getter, @ToString, @EqualsAndHashCode, @RequiredArgsContructor
@setter가 포함된다는 게 이슈 사항이 될 수도 있겠지만, 우선은 필요한 부분은 포함하면서 깔끔하게 표현하려고 했습니다.
원하신다면 수정하도록 하겠습니다!

2022-05-08 07:44 UTC, jaeesu commented
추가적으로 현재 팔로잉, 팔로우 목록에 정렬 방식이 들어가있지 않은 상태입니다.
이 부분은 버그 등록해두고 프론트 분들과 상의하여 추후에 수정하도록 하겠습니다.
우선은 빨리빨리 기능을 개발하는 것에 초점을 맞출게요! 코드 퀄리티 생각하다보니 너무 늦어진 것 같네요 🥲

2022-05-08 09:42 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/common/config/SecurityConfig.java
> +                .antMatchers(HttpMethod.GET,"/v1/users/following/from", "/v1/users/following/to").permitAll()
저 부분을 추가하지 않으면 controller에서 오류가 발생해서 추가하신 건가 궁금해서 여쭤본 겁니다!

2022-05-08 09:45 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/follow/ui/dto/FollowResponse.java
> +public class FollowResponse {
충환님이 어떻게 생각하시는지 들어보고 결정하는게 좋을 것 같네요!

2022-05-08 09:46 UTC, seongho-joo approved these changes
고생하셨습니다!

2022-05-09 00:43 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/follow/ui/FollowController.java
>      public CommonResponse createFollow(@RequestParam("from_member") Long fromMemberId, @PathVariable("toUserId") Long toMemberId) {
PathVariable과 파라미터 명을 다르게 하신 이유가 있으신가요? 같게 하면 생략이 가능해서 더 편할것 같아서 질문드립니다!

2022-05-09 00:43 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/follow/ui/dto/FollowResponse.java
> +public class FollowResponse {
DTO라서 크게 상관은 없을 것 같지만 Getter, NoArgsConstructor, 정적 팩터리 메서드를 만들기 위한 AllArgsConstructor 있어도 좋을 것 같네요. 그리고 MemberDto를 static으로 작성하신 이유가 있나요?

2022-05-09 02:12 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/follow/ui/FollowController.java
>      public CommonResponse createFollow(@RequestParam("from_member") Long fromMemberId, @PathVariable("toUserId") Long toMemberId) {
일단은 크게 의식하지 않고 작성한 부분이라 다르게 했다는 생각을 못했네요
애노테이션과 함께 pathVariable을 적어준 건 그냥 저의 코딩 스타일입니다! 저는 한 번에 알아볼 수 있게 명시적으로 적어주는 것을 좋아해서 항상 적는 편입니다.
일관성을 유지하지 위해 toUserId를 toMemberId로 바꾸겠습니다.
그래도 애노테이션과 함께 변수명은 써줬으면 하는데 어떠신가요?

2022-05-09 02:14 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/follow/ui/FollowController.java
>      public CommonResponse createFollow(@RequestParam("from_member") Long fromMemberId, @PathVariable("toUserId") Long toMemberId) {
네 저도 어노테이션과 함께 사용하는데 toUserId, toMemberId를 통일하면 @PathVariable 우측에 있는 괄호를 생략해도 된다는 말이었어요

2022-05-09 02:24 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/follow/ui/dto/FollowResponse.java
> +public class FollowResponse {
NoArgsConstrctor, AllArgsConstructor는 필요할 때, 추가하면 될 것 같은데 확장성을 미리 고려하고 지금 작성하는게 나을까요?

내부 클래스는 암묵적으로 외부 클래스와 단절함을 나타내도록 static으로 작성하는 것을 권장합니다. MemberDto에서 FollowResponse의 자원을 사용할 일이 없기 때문에 static으로 만들었습니다.
추가적으로 이 부분은 아직 확실히 이해하진 못했지만, 외부 참조가 가능하다는 것은 외부를 통해 내부를 참조할 수 있다는 것이 돼서 메모리 누수의 가능성이 있다고 합니다!

2022-05-09 02:27 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/common/config/SecurityConfig.java
> +                .antMatchers(HttpMethod.GET,"/v1/users/following/from", "/v1/users/following/to").permitAll()
permitAll()이 토큰없이도 접근할 수 있다. 누구라도 접근할 수 있다는 의미입니다.
~/from, ~/to 이것들은 로그인없이 들어온 사용자라도 볼 수 있어야 하기 때문에 열어뒀습니다!
저 조건을 달지 않았을 때, 모든 api는 토큰 필터만 통과하면 인가되는 것으로 알고 있습니다. 하지만 저희 서비스처럼 role이 있는 경우는 role에 따른 인가 조건을 설정해주는 것이 맞다고 생각합니다.

2022-05-09 04:01 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/follow/ui/FollowController.java
>      public CommonResponse createFollow(@RequestParam("from_member") Long fromMemberId, @PathVariable("toUserId") Long toMemberId) {
저는 통일을 하더라도 명시적으로 적어준다는 얘기였습니다! 제거하도록 할까요?

2022-05-09 13:39 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/follow/ui/FollowController.java
>      public CommonResponse createFollow(@RequestParam("from_member") Long fromMemberId, @PathVariable("toUserId") Long toMemberId) {
이 부분은 생각해보니까 Long MemberId에서 MemberId가 이미 명시적으로 나타내준 건데 굳이 또 넣을 필요는 없을것 같네요! 너무 습관적으로 했던 듯 합니다....ㅎㅎ 제거하도록 할게요!

2022-05-10 04:58 UTC, ch0213 approved these changes
고생하셨습니다!

2022-05-10 05:38 UTC, merged