feat: 영상 좋아요 기능 추가
numbble/backend pull request #31
Opened 2022-05-09 17:31 UTC by jaeesu

###  :speech_balloon: Motivation
* 팔로우 기능과 크게 다르지 않게 개발했습니다.
* 인수테스트 시, 정보를 가진 MockUser를 생성하기 위하여 @MockCustomUser 애노테이션과 테스트용으로 사용할 SecurityContext와 내부에 사용자를 등록하는 메서드를 작성했습니다.
* security 인가 조건에 hasRole을 설정하기 위해 Member Role 설정을 수정했습니다. 
  * security context에 "ROLE_**"의 형태로 권한 저장
  * security 인가 설정에는 ROLE_이 없는 **로 들어가야 하므로 Role을 MEMBER, ADMIN으로 수정

### :exclamation: Key changes
* 좋아요 등록 여부 확인 api
  * 인가되고 난 후에는 오류가 나는 경우가 없음 (true, false만 반환하면 되기 때문)
* 좋아요 등록 api
  * 예외 사항
    * 존재하지 않는 영상에 등록 요청
    * 이미 좋아요를 등록한 영상에 등록 요청
* 좋아요 삭제 api
  * 예외 사항 
    * 존재하지 않는 좋아요를 삭제 요청
    * 본인이 등록하지 않은 좋아요를 삭제 요청

###  :pencil2: To Reviewers
* reviewer들에게 전하고 싶은 말이 있다면 적어주세요.

2022-05-09 17:35 UTC, jaeesu commented
이전 pr이 아직 머지되지 않은 상태라 commit이 중복되어 요청되었네요! 이전 pr이 merge되면 자동으로 그 부분 commit은 빠지게 되나요?
이대로 놔둬도 문제는 없겠지만, 혹시 이전 pr 의 커밋을 분리,제거할 수 있는 방법을 아시는 분은 알려주세요!

2022-05-10 05:00 UTC, ch0213 approved these changes
고생하셨습니다!

2022-05-10 05:29 UTC, seongho-joo requested changes

2022-05-10 05:29 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/testCommon/mockUser/WithMockCustomUser.java
> +}
이렇게 하면 토큰 값을 안넘겨줘도 @LoginUser를 사용할 수 있나요?

2022-05-10 05:29 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/likevideo/acceptance/LikeVideoAcceptanceTest.java
> +
repository를 안쓰시고 entity manager를 사용하신 이유가 있으신가요?

2022-05-10 05:36 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/testCommon/mockUser/WithMockCustomUser.java
> +}
네! 컨트롤러에서 WithMockCustomUSer를 생성하면서 만든 context에서 인증 정보를 인식하는 것 같습니다
WithMockUser를 사용할 때도 되긴 하지만, 저희가 원하는 사용자 정보를 들고 있지 않아 오류가 발생합니다

2022-05-10 05:37 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/likevideo/acceptance/LikeVideoAcceptanceTest.java
> +
persist만 하는 간단한 기능이기에 의존성 주입하는 한 두줄도 줄이고 싶어서 entitymanger를 사용했습니다!

2022-05-10 05:38 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/testCommon/mockUser/WithMockCustomUser.java
> +}
어제 인수테스트를 하면서 WithMockUser를 사용해도 안되서 고생 좀 했었는데,, 현재 브랜치에 적용해서 인수 테스트를 해야겠네요!

2022-05-10 05:40 UTC, seongho-joo approved these changes
고생하셨습니다!

2022-05-10 06:12 UTC, merged