feat: 영상 조회 기능 추가
numbble/backend pull request #35
Opened 2022-05-10 13:23 UTC by seongho-joo

###  :speech_balloon: Motivation
* 여러 영상들을 조회할 때 cursor-based 페이징을 적용하여 개발했습니다.
* querydsl을 사용하지않고 jpql를 사용했습니다.

### :exclamation: Key changes
* s3에 파일을 등록할 때 파일의 null 여부 확인을 추가했습니다.
* 조회 api, 서비스 개발
  * 모든 영상 조회 (조회순, 좋아요순)
  * 영상 상세 정보 조회
  * 회원의 영상 목록 조회

###  :pencil2: To Reviewers
* 회원의 영상 목록도 구현했는데 회원 서비스 구현할 때 옮겨서 사용하시면 될 것 같습니다

2022-05-11 01:24 UTC, jaeesu commented on build.gradle
> +	implementation 'com.google.code.findbugs:jsr305:3.0.2'
어떤 기능을 위한 종속성인가요?

2022-05-11 02:23 UTC, jaeesu requested changes

2022-05-11 02:23 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/acceptance/VideoAcceptanceTest.java
> +
인수 테스트는 시나리오 기반이라 꼭 하나의 기능에 대해 테스트할 필요는 없는건가요?
하나의 테스트에 여러 res와 res 검증이 들어가서 직관적으로 확인이 어려운데 나눠서 작성할 수 있는 방법은 없을까요?

2022-05-11 02:23 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/acceptance/VideoAcceptanceTest.java
> +    @Test
이런 시나리오라면 도메인 검증이 필요하긴 하겠네요! 그런데 저는 이 시나리오가 굳이 필요한가라는 생각이 들어요!
저장과 삭제가 에러없이 작동하는 것만 보여주면 이 부분에 대해서는 확인이 되었다고 봐도 무방하지 않나 싶습니다.
그리고 시나리오만 따로 문서로 작성해주시면 좋을 것 같아요!

2022-05-11 02:23 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/acceptance/VideoAcceptanceTest.java
> +    @Test
저는 이 에러의 경우도 400으로 뒀는데 401로 수정해야겠네요! 👍 😄

2022-05-11 02:23 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/acceptance/VideoAcceptanceTest.java
> +        res.andExpect(status().isOk())
조회수가 똑같은 경우 어떻게 정렬되는지 검증이 필요해보입니다!

2022-05-11 02:23 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/domain/VideoRepositoryTest.java
> +            Video mockVideo = Video.builder().id(100L).build();
mockvideo 만들지 않고 아무 아이디값이나 바로 넣어주면 될 것 같습니다

2022-05-11 02:23 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/domain/VideoRepositoryTest.java
> +            Video findVideo = videoRepository.findById(savedVideo.getId())
저장한 video를 한 번 더 조회하기 전에 컨텍스트가 초기화 되지 않아서 db에서 조회하지 않고, 캐쉬값을 가져옵니다
애초에 video를 한 번 더 조회할 이유가 없는 것 같은데 한 번 더 조회하신 이유가 있나요?

2022-05-11 02:23 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/domain/VideoRepositoryTest.java
> +
258번 줄 update와 265번 줄 update가 무슨 차이인가요?
update를 2번 하신 이유가 궁금합니다

2022-05-11 02:23 UTC, jaeesu commented on src/test/java/numble/team4/shortformserver/video/domain/VideoRepositoryTest.java
> +            Video findVideo = videoRepository.findById(savedVideo.getId())
여기서도 video를 다시 조회할 이유는 없을 것 같아요

2022-05-11 03:53 UTC, seongho-joo commented on build.gradle
> +	implementation 'com.google.code.findbugs:jsr305:3.0.2'
build할 때 javax.annotation.meta.When의 경고를 해결하려고 추가한 종속성입니다.

2022-05-11 03:53 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        memberRepository.findById(loggedInMember.getId()).orElseThrow(NotExistMemberException::new);
회원인지 게스트인지 판별하려고 조회를 추가해놨는데 existById로 수정했습니다.

2022-05-11 03:55 UTC, jaeesu commented on build.gradle
> +	implementation 'com.google.code.findbugs:jsr305:3.0.2'
javax.annotation.meta.When은 어디에 사용하셨나요?
When이 어떤 역할을 하는지 등 조금 더 자세한 설명 부탁드립니다!

2022-05-11 03:56 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        memberRepository.findById(loggedInMember.getId()).orElseThrow(NotExistMemberException::new);
게스트인지가 익명의 사용자를 말씀하시는건가요?
@LoginUser로 문제없이 받아왔다면 이미 회원임이 확인되었다는 것인데, 이것과는 별개의 것을 말씀하시는 건가요?

2022-05-11 04:20 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +        }
아녀 포스트맨 동작확인은 아직 해보지 않았습니다 한번 해볼게요!

2022-05-11 04:22 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/VideoRepository.java
> +
Sort 객체가 쿼리 작성보다 더 나을까요?

2022-05-11 04:23 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +        }
제가 지금 문제가 생긴 equals가 테스트에서는 context clear 하지 않고 통과했다가, 포스트맨 테스트하면서 발견한거라... 😢 
포스트맨 체크가 저도 깜빡할 때가 많아서 이슈에 등록해놓고 확인하시면 좋을 것 같아요~

2022-05-11 04:26 UTC, seongho-joo commented on build.gradle
> +	implementation 'com.google.code.findbugs:jsr305:3.0.2'
이 부분은 gradle 빌드할때 발생 했었는데 좀 더 알아본 후에 설명드리겠습니다!

2022-05-11 04:29 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        memberRepository.findById(loggedInMember.getId()).orElseThrow(NotExistMemberException::new);
네 맞습니다. 지금 #34 를 개발하면서 저 부분은 필요없겠다 생각이 들어 제거를 했습니다.

2022-05-11 04:34 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/dto/VideoResponse.java
네 맞습니다! response에서는 validation 확인을 하지않나요?

2022-05-11 05:49 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +        }
지금 video-#27 브랜치로 돌아가려면 엄청난 수정을 다시 해야해서,, 도메인 수정 카테고리 완료 후 포스트맨 체크 해보겠습니다!

2022-05-11 07:23 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/VideoRepository.java
>  }
인수테스트에 이런 경우를 넣어놨는데  아이디 값 비교를 안해서 한번 확인해보고 말씀드릴게요!

2022-05-11 07:24 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/video/domain/VideoRepositoryTest.java
> +            Video findVideo = videoRepository.findById(savedVideo.getId())
아 이코드는 flush, clear를 했을 때 작성했던 코든데 제가 수정을 안했네요! #34 pr할 때 수정해서 올리겠습니다!

2022-05-11 07:26 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/video/domain/VideoRepositoryTest.java
> +
이 경우 `modified_at` 값이 변경되는지 확인하려고 작성했는데 합쳐서 작성해도 되겠네요 !

2022-05-11 07:28 UTC, seongho-joo commented on src/test/java/numble/team4/shortformserver/video/domain/VideoRepositoryTest.java
> +            Video mockVideo = Video.builder().id(100L).build();
그렇네요! 쓸데없는 코드들이 너무 많네요..😅

2022-05-11 07:51 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/VideoRepository.java
>  }
테스트를 진행해보니 같을 경우 id 값이 작은 순서대로 정렬되는데 이대로 둬도 되지않을까 합니다.

2022-05-11 10:44 UTC, jaeesu commented on build.gradle
> +	implementation 'com.google.code.findbugs:jsr305:3.0.2'
네 알겠습니다!

2022-05-11 10:45 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +        }
넵! 참고로 다른 브랜치로 돌아갈 때는 git stash를 사용할 수 있습니다!

2022-05-11 10:47 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/VideoRepository.java
> +
정렬 기준을 파라미터로 받으면 Sort 객체로 여러 함수를 합칠 수 있지 않을까요?
Sort 객체를 이용하는게 조금이나마 더 orm에 가까운 방식이니까 할 수 있다면 Sort를 사용하는 것이 나을 것 같습니다.

2022-05-11 10:49 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/VideoRepository.java
>  }
제 경험상으로 id값 순서대로 정렬이 안 된 적이 있었습니다! 그 때는 작성 시각을 기준으로 했는데 작성 시각이 똑같은 것들끼리 순서가 바뀌었습니다. 데이터가 많아질 경우를 생각해서 정렬 조건을 추가하는 게 좋을 것 같습니다

2022-05-11 12:49 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/VideoRepository.java
> +
query에 페이지 관련된 부분이 없는데 spring이 pageable 적용 시켜주나요?!

2022-05-11 13:18 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/VideoRepository.java
> +
Sort 객체를 이용할 수 있다고 생각했는데 cursor-based니까 spring data jpa가 자동 생성 해주는 걸로는 어려울 수도 있을 것 같네요! 😢

2022-05-11 13:39 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/VideoRepository.java
>  }
<img width="677" alt="image" src="https://user-images.githubusercontent.com/50989437/167863344-347a8565-066e-4606-b166-2535a63733e9.png">

포스트맨으로 사용자 영상을 조회해보니, 아이디값이 뒤죽박죽으로 나오네요!

2022-05-11 13:48 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/VideoRepository.java
>  }
커서 기반을 사용했을때 인가요?

2022-05-11 13:53 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/VideoRepository.java
>  }
방금 저도 비디오들을 여러개 만든 후  hits와 likes를 0으로 두고 테스트를 진행하니 id 값이 Null일 때는 id가 작은 순서대로 정렬이 되는데 id가 존재할 경운 0보다 작기때문에 아무것도 뜨지않더라구요 이 부분을 수정해야할 것 같습니다.

2022-05-11 15:53 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +        }
#36 수정 코드로 포스트맨 체크를 해보니 수정, 삭제할 때 validateAuthor 정상적으로 돌아갔습니다.!

2022-05-11 16:00 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/VideoRepository.java
> +
> query에 페이지 관련된 부분이 없는데 spring이 pageable 적용 시켜주나요?!

이 부분에 대한 답변이 늦었네요. pageable을 사용하면 JPA에서 자동으로 limit를 걸어주는 것 같습니다!

2022-05-12 10:58 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/likevideo/domain/LikeVideo.java
> +    public void like() {
이 함수 만들지 말고 service 에서 video.increaseLikeCount() 바로 호출하는 게 나을 것 같아요

2022-05-12 11:02 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void updateCursor() {
이 함수는 어떤 역할인가요?

2022-05-12 11:03 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/dto/VideoResponse.java
> +
이 부분 확인해주세요

2022-05-12 11:05 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/infrastructure/VideoCustomRepositoryImpl.java
> +
cursor보다는 maxNum이 낫지 않을까요? 함수를 보지않고는 직관적으로 알기 어려운 것 같습니다

2022-05-12 11:06 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +        @PageableDefault Pageable pageable
한 페이지당 컨텐츠 수는 수정 안하셨나요?

2022-05-12 11:32 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +    public CommonResponse<VideoResponse> findByIdVideo(@PathVariable Long videoId) {
메서드명 findByVideoId나 findById로 수정해주세요

2022-05-12 11:33 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +    @GetMapping
동영상 목록 조회 / 동영상 하나 조회 dto 따로 만들어서 반환값 다르게 하는 게 좋지 않을까요?

2022-05-12 13:40 UTC, ch0213 requested changes

2022-05-12 13:40 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/member/member/domain/Member.java
> +}
개행 추가하면 좋을 것 같습니다

2022-05-12 13:40 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        if (Objects.isNull(videoId)) {
이 부분은 Service말고 repository에서 처리해야할 것 같습니다

2022-05-12 13:40 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        if (Objects.isNull(videoId)) {
이 부분도요!

2022-05-12 13:40 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/infrastructure/VideoCustomRepositoryImpl.java
> +    private BooleanExpression cursorId(String cursor, String sortBy) {
if-else 구문 반복보다는 early return을 하면 좋을 것 같아요

2022-05-12 14:22 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/likevideo/domain/LikeVideo.java
> +    public void like() {
네 알겠습니다!

2022-05-12 14:26 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void updateCursor() {
이 부분은 커서 컬럼을 따로 만들어 커서 기반 페이징할 때 사용하려고 했는데 제가 피그마를 잘못봐서 전체 영상 조회가 필요가 없어졌습니다. 전체 영상 조회만든 코드를 제거하면서 같이 제거할 생각입니다

2022-05-12 14:30 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +        @PageableDefault Pageable pageable
검색 기능을 개발할 때 컨텐츠 수를 정해서 하겠습니다

2022-05-12 14:41 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
cursor 컬럼이 무슨 의미인지 모르겠습니다

2022-05-12 14:43 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        if (Objects.isNull(videoId)) {
검색기능할 때 참고해서 개발하겠습니다!

2022-05-12 14:44 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/infrastructure/VideoCustomRepositoryImpl.java
> +    private BooleanExpression cursorId(String cursor, String sortBy) {
early를 알아보고 적용하도록 하겠습니다

2022-05-12 14:47 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
cursor 컬럼으로 커서 기반 페이징 조건을 두려고했는데 필요가 없어져서 삭제했습니다.

2022-05-12 16:08 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +        @PageableDefault Pageable pageable
프론트에 제대로 완성된 api를 빨리 넘겨줘야돼서 지금 수정하고 넘어갔으면 하는데 어렵나요?

2022-05-12 16:09 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +        @PageableDefault Pageable pageable
검색이 없을 경우 모든 영상 조회 기능이 없습니다!

2022-05-12 16:12 UTC, seongho-joo commented on build.gradle
> +	implementation 'com.google.code.findbugs:jsr305:3.0.2'
네 제거하도록 하겠습니다!

2022-05-12 16:12 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
여기서는 cursor가 사라지지 않은 것으로 나오는데, 다른 pr에서 삭제한 게 적용된건가요? 왜 현재 기능 개발이 다른 pr로 이어지는 건지 모르겠습니다.

2022-05-12 16:14 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void updateCursor() {
추천 영상, 인기 영상이 전체 영상 조회 아닌가요? 아니라면 말씀하신 전체 영상 조회가 어떤건가요?

2022-05-12 16:16 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
삭제 적용이 안됐나요? 전 삭제 되어있는 것으로 나와있습니다

2022-05-12 16:20 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void updateCursor() {
<img width="735" alt="스크린샷 2022-05-13 오전 1 20 25" src="https://user-images.githubusercontent.com/45463495/168122371-6f8b3e24-d6ab-414c-b625-499a8a43ccf8.png">

피그마를 확인 해보니 추천 영상, 인기 영상이 아니라 키워드더라구요

2022-05-12 16:43 UTC, ch0213 requested changes

2022-05-12 16:43 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/aws/application/AmazonS3Uploader.java
> +        if (Objects.isNull(file) || file.isEmpty()) {
둘 다 null을 확인하는 것 같은데 추가하신 이유가 있나요?

2022-05-12 16:43 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/likevideo/application/LikeVideoService.java
>          LikeVideo likeVideo = LikeVideo.fromMemberAndVideo(member, video);
이펙티브 자바 아이템1을 보면 관용적으로 사용하는 메서드 명명 규칙이 있는데, 여러 매개변수를 받아 적합한 타입의 인스턴스를 반환하는 메서드는 보통 "of"로 하더라구요 ㅎㅎ

2022-05-12 16:43 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/likevideo/application/LikeVideoService.java
> +        likeVideo.getVideo().decreaseLikeCount();
likeVideo에 decreaseLikeCount()를 만드는건 어떨까요? 해당 메서드에서는 위임만 하구요

2022-05-12 16:48 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/aws/application/AmazonS3Uploader.java
> +        if (Objects.isNull(file) || file.isEmpty()) {
null과 비어있는 것은 다르다고 생각해서 추가해놨습니다. 테스트 결과 파일을 보내지 않았을 경우 isNull에 걸리고 `byte[] {}`일 경우 isEmpty에 걸립니다!

2022-05-12 16:53 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/likevideo/application/LikeVideoService.java
> +        likeVideo.getVideo().decreaseLikeCount();
이 부분은 재희님 피드백을 받고 수정을 했어서 재희님의 의견이 필요할 것 같네요
@jaeesu 어떤 것이 더 나은 것 같나요? 전 충환님 말씀처럼 unlike를 만들어 video 에서 처리하는 것이 좀 더 나을 것 같습니다

2022-05-12 16:53 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/likevideo/application/LikeVideoService.java
>          LikeVideo likeVideo = LikeVideo.fromMemberAndVideo(member, video);
네! 참고하겠습니다!

2022-05-12 16:57 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/member/member/domain/Member.java
> +}
개행 추가했습니다!

2022-05-12 17:12 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/likevideo/application/LikeVideoService.java
> +        likeVideo.getVideo().decreaseLikeCount();
처음에는 단순 위임을 하게 되면서, 메서드를 한 번 더 거쳐야 하는 것 때문에 '이 정도는 그냥 비즈니스 로직에서 할 수 있지 않나'하는 생각에 수정 요청을 드렸습니다.
지금 생각해보니, 결국 Likevideo가 가져야 할 책임을 밖에다 두는 게 더 찝찝한 결과가 되네요...ㅎㅎㅎ
메서드를 만드는 것이 좋을 것 같습니다! 괜히 번거롭게 했네요 😂

2022-05-12 17:21 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/likevideo/application/LikeVideoService.java
> +        likeVideo.getVideo().decreaseLikeCount();
아닙니다! 🙂

2022-05-12 17:23 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void updateCursor() {
키워드 기반 추천, 인기 영상인건가요?

2022-05-12 17:24 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
코멘트에 언급된 파일명을 바로 누르면 새롭게 적용된 게 안 뜨네요ㅠ 제가 잘못 확인했었습니다!
삭제된 것 확인했습니다~

2022-05-12 17:26 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/dto/VideoResponse.java
>      private Long id;
jsonnaming이나 jsonproperty 등을 사용해서 api 반환 시에만 snake 형식으로 알아서 바뀌도록 할 수 있습니다

2022-05-12 17:32 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/dto/VideoResponse.java
>      private Long id;
이런 방식ㅇ ㅣ있었군요! 모르는게 너무 많네요 😅

2022-05-12 17:34 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/Video.java
> +    public void updateCursor() {
저 회색 칸이 영상이 아니라 키워드인 것 같습니다! 정호님에게 한번 말씀드려볼게요

2022-05-12 17:38 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/dto/VideoResponse.java
>      private Long id;
<img width="1988" alt="스크린샷 2022-05-13 오전 2 38 38" src="https://user-images.githubusercontent.com/45463495/168135632-642bff4c-888c-4440-8553-c3bb09ea0917.png">

요즘은 jsonproperty을 사용하나보네요

2022-05-13 05:37 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/dto/VideoResponse.java
>      private Long id;
저는 jsonNaming을 사용했는데, 뭔가 버전이 다른가요?

2022-05-13 05:38 UTC, jaeesu approved these changes

2022-05-13 08:14 UTC, ch0213 approved these changes
고생하셨어요!

2022-05-13 08:14 UTC, merged