feat: 비디오 도메인 변경 및 카테고리 기능 구현
numbble/backend pull request #36
Opened 2022-05-11 09:11 UTC by seongho-joo

###  :speech_balloon: Motivation
* 비디오와 카테고리 연관관계를 N:1 단방향 매핑으로 구현했습니다.
* 카테고리 이름은 unique 제약조건 지정해줬습니다.

### :exclamation: Key changes
* 테이블 생성 SQL 추가
* 비디오 테이블 컬럼과 카테고리 매핑으로 인한 비디오 관련 모든 코드들 수정했습니다.

###  :pencil2: To Reviewers
* #35 피드백들 video-category 브랜치에서 수정했습니다.

2022-05-11 09:13 UTC, seongho-joo commented
#35 PR merge가 되지않아서 이전 PR에서 커밋들이 같이 올라와있네요🥲

2022-05-11 11:03 UTC, jaeesu requested changes

2022-05-11 12:51 UTC, ch0213 requested changes

2022-05-11 12:51 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/member/member/domain/Member.java
>  @Builder
클래스 레벨로 Builder어노테이션을 썼을때 장점이 무엇인가요?

2022-05-11 12:51 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/member/member/domain/Member.java
> +}
개행 추가하면 좋을 것 같습니다~

2022-05-11 12:51 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        Page<VideoResponse> videos;
이 조건 확인을 queryDsl로 처리하건 어떨까요?

2022-05-11 12:51 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        Page<VideoResponse> videos;
밑에 메서드도 비슷하게 구현돼있는데 service layer말고 데이터를 조회할 때 확인하면 좋을 것 같아요~

2022-05-11 12:51 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/category/application/CategoryService.java
> +            .map(CategoryDto::create)
사소한거긴 하지만 다른 dto의 생성 메서드랑 이름을 맞추면 좋을것같아요! ex) from

2022-05-11 12:51 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/domain/VideoRepository.java
> +    Page<Video> findAllSortByLikeCount(Pageable pageable);
위에 @Query로 작성해주신 이유가 있나요? Spring Data JPA에서는 저렇게 메서드명만 규칙에 맞게 작성하면 동작이 되는걸로 알고있습니다.

2022-05-11 12:51 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +    public CommonResponse<List<VideoResponse>> findAllVideos(
Controller는 요청을 전달해주는 역할만 하는게 좋을 것 같아요. 또한 pageable에 정렬 기준도 포함할 수 있습니다.

2022-05-12 08:24 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/member/member/domain/Member.java
>  @Builder
생성자를 따로 생성안하고 원하는 값만 넣을 수 있는게 장점이라고 생각합니다!

2022-05-12 08:26 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/member/member/domain/Member.java
> +}
어떤 라인에 개행인가요?

2022-05-12 08:33 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +        Page<VideoResponse> videos;
#35 에서 querydsl 적용해서 올려놨습니다 리뷰 부탁드릴게요 🙂

2022-05-12 08:36 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/domain/VideoRepository.java
> +    Page<Video> findAllSortByLikeCount(Pageable pageable);
Spring Data JPA 사용이 이번이 처음이라 잘 몰랐네요! 위에 댓글 참고해주세요!

2022-05-12 08:38 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +    public CommonResponse<List<VideoResponse>> findAllVideos(
if 문을 보고 말씀하시는거면 수정해놓겠습니다!

2022-05-12 09:47 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/category/domain/Category.java
> +public class Category extends BaseTimeEntity {
AllArgsConstructor는 테스트할 때 필요해서 NoArgsConstructor만 수정했습니다.

2022-05-12 11:10 UTC, jaeesu requested changes

2022-05-12 11:10 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +
videoId가 어떤 값이 되든 currentPage는 0으로 나타나서 page 정보는 반환하지 않아도 될 것 같습니다

2022-05-12 11:54 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/application/VideoService.java
> +
`Page<T>` 리턴 타입을  `List<T>` 수정하면 되겠죠?

2022-05-12 12:05 UTC, seongho-joo commented on src/main/resources/init.sql
> -    ADD CONSTRAINT FOREIGN KEY (member_id) REFERENCES member (id)
DDL과 DML을 분리하고 yml 설정을 따로 안건드려도 `data.sql`의 쿼리가 실행되는 이유 알고 계실까요?

2022-05-12 17:31 UTC, jaeesu commented on src/main/resources/init.sql
> -    ADD CONSTRAINT FOREIGN KEY (member_id) REFERENCES member (id)
항상 디비 초기화 되도록 해뒀으면 schema.sql / data.sql 이걸 디폴트 파일명으로 하고 있어서 알아서 찾는 걸로 알고 있습니다. 정확히 어떤 속성때문에 적용된다.는 잘 모르겠네요 😅

2022-05-12 17:49 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/category/application/CategoryService.java
> +    public List<CategoryDto> findCategories() {
오름차순으로 하면 기타가 두 번째로 와서 아래와 같이 id 오름차순으로 해놓겠습니다!
<img width="80" alt="스크린샷 2022-05-13 오전 2 44 50" src="https://user-images.githubusercontent.com/45463495/168137211-a73ca62a-0394-4f7d-96d5-1bb1b4ef6fbb.png">

2022-05-12 17:51 UTC, seongho-joo commented on src/main/resources/init.sql
> -    ADD CONSTRAINT FOREIGN KEY (member_id) REFERENCES member (id)
그렇군요! 알려줘셔서 감사합니다!

2022-05-13 05:39 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/category/application/CategoryService.java
> +    public List<CategoryDto> findCategories() {
넵!

2022-05-13 05:40 UTC, jaeesu approved these changes

2022-05-13 08:14 UTC, ch0213 approved these changes
고생하셨어요!

2022-05-13 09:04 UTC, merged