feat: 채팅 기능 구현 및 소셜 로그인 리팩토링
numbble/backend pull request #44
Opened 2022-05-12 16:08 UTC by ch0213

###  :speech_balloon: Motivation
* 채팅 기능 구현 및 소셜 로그인 리팩토링 했습니다. 추가 요구사항도 반영했습니다.

### :exclamation: Key changes
* websocket, stomp를 활용해 채팅 기능 구현
* oauth2-client를 활용해 소셜 로그인 구현 - 기존 직접 구현 코드 삭제
* access denied에 대한 예외처리 구현
* 최근 로그인 일자 업데이트 기능 구현
* Member에 OAuthProvider 필드 추가 - 이미 가입된 회원인지를 검사할 때 소셜로그인 제공사에서 반환한 id와 소셜로그인 제공사명을 함께 검색

2022-05-12 16:35 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/member/auth/application/creator/KakaoMemberCreator.java
> +                (Long) attribute.get("id"),
이 부분은 생각해보셨을 것 같지만 추후 수정을 위해 코멘트 남겨두겠습니다!
소셜 제공사가 여러개라고 생각했을 때, 제공해주는 아이디를 그대로 저장하면 안 될 것 같습니다. 아이디가 무조건 동일하지 않다는 것을 보장할 수 없으니까요. provider + id 복합키로 가거나 provider + id 문자열로 아이디를 저장해야 할 것 같습니다

2022-05-12 17:22 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/member/auth/application/creator/KakaoMemberCreator.java
> +                (Long) attribute.get("id"),
네 그래서 회원을 저장할 때 소셜 로그인 제공사로부터 받은 id와 Provider를 함께 저장합니다!

2022-05-12 17:22 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/chat/application/dto/ChatMessageResponse.java
> +}
이름도 같이 넘겨주는게 좋겠군요 ㅎㅎ 피드백 감사합니다.

2022-05-13 08:18 UTC, jaeesu requested changes

2022-05-13 08:18 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/chat/infrastructure/ChatRoomRepositoryImpl.java
> +    @Override
채팅 목록도 커서 베이스로 이뤄지지 않나요?

2022-05-13 08:18 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/member/auth/application/creator/KakaoMemberCreator.java
> +                (Long) attribute.get("id"),
지금처럼 했을 때, apple에서 아이디가 12345인 사용자가 있고, kakao에서 아이디가 12345인 사용자가 있다면 Member의 id 값 자체가 겹칠 수 있다는 의미였습니다!

2022-05-13 08:18 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/chat/ui/ChatRoomController.java
> +    public CommonResponse<Void> createChatRoom(@LoginUser Member member, @RequestBody CreateChatRoomRequest request) {
@valid 달아주세요!

2022-05-13 08:18 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/chat/ui/ChatMessageController.java
> +    public void sendMessage(ChatMessageRequest request) {
여기서는 @valid를 달 수 없나요? 
roomId가 null일 경우 어떻게 처리되나요?

2022-05-13 08:19 UTC, jaeesu commented on src/main/resources/application-oauth.yml
> +            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
환경변수 추가된 부분 .env 공유해주시고, github secrets 수정, pr 템플릿 수정, 빌드 배포 스크립트 수정해주세요

2022-05-13 10:55 UTC, ch0213 commented on src/main/resources/application-oauth.yml
> +            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
> baseUri, action, registrationId는 어디서 주입되나요?

oauth2-client 에서 자동으로 주입해줍니다! oauth2-client를 사용하지 않게되어서 이 부분은 지울 예정입니다.

2022-05-13 10:56 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/chat/infrastructure/ChatRoomRepositoryImpl.java
> +    @Override
수정하겠습니다!

2022-05-13 11:36 UTC, seongho-joo approved these changes
고생하셨습니다!

2022-05-13 13:06 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/member/auth/application/creator/KakaoMemberCreator.java
> +                (Long) attribute.get("id"),
제가 userId를 착각했었네요.
sql은 수정 안 하셨나요? 현재 pr에 올라온게 없네요!

2022-05-13 13:08 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/chat/ui/ChatMessageController.java
> +    public void sendMessage(ChatMessageRequest request) {
이 부분 적절한 어노테이션을 찾아서 처리했습니다 👍

2022-05-13 13:10 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/member/auth/application/creator/KakaoMemberCreator.java
> +                (Long) attribute.get("id"),
채팅 기능 수정중인데 한번에 올리겠습니다!

2022-05-14 04:50 UTC, jaeesu commented
init.sql 수정한 부분 올려주세요!

2022-05-14 04:53 UTC, ch0213 commented
> init.sql 수정한 부분 올려주세요!

2022-05-14 13:09 UTC, jaeesu approved these changes

2022-05-14 13:51 UTC, ch0213 commented on src/main/resources/application-oauth.yml
> +            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
> 환경변수 추가된 부분 .env 공유해주시고, github secrets 수정, pr 템플릿 수정, 빌드 배포 스크립트 수정해주세요

기존 env에서 KAKAO_REDIRECT_URL만 삭제했습니다. github secrets, 배포 스크립트에서도 제거했습니다~

2022-05-14 16:29 UTC, merged