feat: 영상 검색 기능 구현
numbble/backend pull request #46
Opened 2022-05-13 12:47 UTC by seongho-joo

###  :speech_balloon: Motivation
* 검색 기능 과 영상 서비스는 관심사가 다르다고 생각하여 영상 서비스와 분리하여 개발했습니다.
* 커서 기반을 사용할 시 비교값이 유일하지않으면 같은 값을 가질 때 제외돼서 정렬됩니다. 따라서 비교 값과 id값을 이용해 공식을 만들어 unique 값을 생성했습니다. 

### :exclamation: Key changes
* 키워드로 영상 검색 api 구현
* 검색 페이지의 영상 top10 조회 api 구현

###  :pencil2: To Reviewers
- 유니크 값 생성 공식은 아래 링크를 참조했습니다.
[커서 기반 페이지네이션 (Cursor-based Pagination) 구현하기](https://velog.io/@minsangk/커서-기반-페이지네이션-Cursor-based-Pagination-구현하기)

2022-05-13 13:47 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/infrastructure/VideoCustomRepositoryImpl.java
> +    }
sortBy가 hits / likes / null 중에 하나라는 것이 무조건 보장된다면 코드를 이렇게 수정할 수 있을 것 같아요!

`
private OrderSpecifier<?> videoSort(String sortBy) {

        if (!StringUtils.hasText(sortBy)) {
            return new OrderSpecifier<>(Order.DESC, video.id);
        }
         return new OrderSpecifier<>(Order.DESC, (sortBy.equals("hits")) ? video.viewCount : video.likeCount);
    }
`

2022-05-13 14:36 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/infrastructure/VideoCustomRepositoryImpl.java
> +    }
아 삼항연산자를 생각못했었네요! 저렇게 수정하겠습니다.

2022-05-14 09:04 UTC, jaeesu requested changes

2022-05-14 09:04 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/infrastructure/VideoCustomRepositoryImpl.java
> +        if (Objects.nonNull(sortBy) && Objects.nonNull(lastId)) {
Objects.nonNull -> StringUtils.hasText 이렇게, stringutils를 사용하는게 더 적합해 보입니다

2022-05-14 09:04 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/infrastructure/VideoCustomRepositoryImpl.java
> +        if (Objects.isNull(cursor)) {
여기도 StringUtils가 적합할 듯 하네요

2022-05-14 09:04 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/infrastructure/VideoCustomRepositoryImpl.java
> +    private StringExpression algorithm() {
좀 더 알기 쉬운 함수명으로 바꿔주세요!

2022-05-14 09:04 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/infrastructure/VideoCustomRepositoryImpl.java
> +    private BooleanExpression likeDescription(String keyword) {
likeDescrtiption, likeTitle을 굳이 따로 함수로 빼야하나?라는 생각이 듭니다.

like 대신 contains를 쓰면 %를 사용하지 않을 수 있습니다

2022-05-14 13:43 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/application/VideoSearchService.java
> +    }
네 알겠습니다!!

2022-05-14 14:20 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/infrastructure/VideoCustomRepositoryImpl.java
> +    private StringExpression algorithm() {
이걸 고민했었는데 막상 떠오르지 않아서 alogrithm으로 했는데 적당한 이름이 없을까요..?

2022-05-14 14:22 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/infrastructure/VideoCustomRepositoryImpl.java
> +    private BooleanExpression likeDescription(String keyword) {
querydsl 사용법을 볼 때 함수로 빼면 좋다는 블로그 글을 보고 참고해서 메서드로 추출해서 사용했는데 그냥 쓰는게 나을까요?

2022-05-14 14:51 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/infrastructure/VideoCustomRepositoryImpl.java
> +    private BooleanExpression likeDescription(String keyword) {
함수로 빼면 좋은 이유가 뭔지 궁금하네요.
다른 부분처럼 파라미터에 따라 구문이 달라진다면, 집중해야 할 쿼리 / 조건 생성의 관심사 분리의 목적으로 분리할 수 있다고 생각합니다.
하지만 이 경우, 쿼리를 확인하기 위해 다른 함수를 또 한번 확인해야 할 이유가 있는지 잘 모르겠습니다.

2022-05-14 16:00 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/infrastructure/VideoCustomRepositoryImpl.java
> +    private BooleanExpression likeDescription(String keyword) {
그 블로그 주소는 기억 안나서 잘 모르겠는데 아마 재사용성때문에 메서드로 빼라고한 것 같습니다. 
이 부분 수정해서 다시 올리겠습니다

2022-05-14 16:46 UTC, ch0213 requested changes

2022-05-14 16:46 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/application/VideoSearchService.java
> +    }
Pageable에서 sort를 처리할 수 있지 않나요?

2022-05-14 16:46 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/ui/VideoSearchController.java
> +        @RequestParam String keyword,
request param이 여러개일때는 ModelAttribute를 생성해서 관리하면 어떨까요?
validation하기도 훨씬 쉬울 것 같아요.

2022-05-14 16:55 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/ui/VideoSearchController.java
> +@RequestMapping("/v1/search")
uri을 
영상 검색 : /v1/videos/keyword-condition
best 영상 : /v1/vidoes/status-condition

이런 식으로 수정하면 좋을 것 같습니다. 이것도 다소 난해한 느낌이 있지만, 현재 uri는 자원보다는 행위에 집중되어 있습니다. 그리고 best 영상의 경우 /v1/search 만 봤을 때, 일반적인 검색 기능으로 생각이 들어요. video에 관련한 건지 알기 어렵다고 생각해요.

2022-05-14 16:57 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/ui/VideoSearchController.java
> +        @RequestParam String keyword,
modelAttribute 검색해도, request body랑 다른점 - 이미지를 받을 수 있다. 이런 정도로만 알고 있었는데, 결국 파라미터 형태니까 묶어서 하나의 객체로 관리할 수 있다는 의미가 있었네요. 👍

2022-05-14 17:07 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/ui/VideoSearchController.java
> +@RequestMapping("/v1/search")
영상 검색 : /v1/videos/search
best 영상 : /v1/videos/search-page 는 어떠신가요?

2022-05-14 17:08 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/ui/VideoSearchController.java
> +        @RequestParam String keyword,
여러 쿼리파라미터를 dto로 받는 방법이 없을까 했는데 modelAttribute를 사용하면 되군요!

2022-05-14 23:56 UTC, jaeesu approved these changes

2022-05-15 00:02 UTC, ch0213 approved these changes

2022-05-15 00:03 UTC, merged