feat: 관리자 페이지 영상 리스트 조회 기능 구현
numbble/backend pull request #52
Opened 2022-05-14 15:40 UTC by seongho-joo

###  :speech_balloon: Motivation
* 리스트 조회 offset 기반 페이징으로 구현했습니다.
* `fetchResult()`가 추후에 사라진다는  경고를 보고 count()를 이용했습니다.

### :exclamation: Key changes
* 관리자에게 영상 수정 및 삭제 권한 추가
* 관리자 페이시 영상 리스트 조회 api 추가

###  :pencil2: To Reviewers
* BeNotAdminException 패키지가 적당한지 봐주시면 감사하겠습니다.

2022-05-14 16:42 UTC, ch0213 requested changes

2022-05-14 16:42 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/common/exception/ExceptionType.java
> +    BE_NOT_AN_ADMIN("관리자만 접근할 수 있습니다.", FORBIDDEN, BeNotAnAdminException.class),
BE_NOT_AN_ADMIN를 제거하고 NOT_AUTHOR_EXCEPTION만 사용해도 될 것 같습니다!
그리고 NOT_AUTHOR_EXCEPTION는 Forbidden이 적절할 것 같네요 ㅎㅎ
이전 pr에서 수정해놨긴 합니다!

2022-05-14 16:42 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/member/dto/MemberEmbeddedDto.java
> +public class MemberEmbeddedDto {
클래스명의 의미가 무엇인가요?

2022-05-14 16:42 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/dto/AdminPageVideoListResponse.java
> +public class AdminPageVideoListResponse {
아까는 생각을 못했는데 클래스명에서 List빼도 될 것 같습니다!

2022-05-14 16:42 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/dto/VideoListResponse.java
> +public class VideoListResponse {
여기도요!

2022-05-14 16:42 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/ui/VideoSearchController.java
> +public class VideoSearchController {
새로운 컨트롤러를 만든 이유가 무엇인가요?

2022-05-14 16:59 UTC, ch0213 requested changes

2022-05-14 16:59 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +    @GetMapping("/admin")
이 url은 어떻게 할지 좀 더 고민해보면 좋을 것 같네요

2022-05-14 17:02 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/common/config/SecurityConfig.java
> +            .authorizeRequests()
요청 메서드끼리 묶지 않고 분리하신 이유가 뭘까요?
저는 요청 메서드끼리 묶어 놓는 것이 빨리 찾아서 추가,수정하기 편하다고 생각했습니다.
도메인이 다른 uri끼리 분리하고자 하신 거라면 한 곳에 몰아넣고, 줄바꿈만 하는게 어떨까요?
```java
 .antMatchers(HttpMethod.GET, "/v1/users/following/from", "/v1/users/following/to",
"/v1/videos/{videoId}").permitAll()
```
이런 식으로요!

```java
 .antMatchers(HttpMethod.GET, 
"/v1/users/following/from", 
"/v1/users/following/to",
"/v1/videos/{videoId}").permitAll()
```
실제로는 이렇게 모두 줄바꿈으로 표시하기도 합니다

2022-05-14 20:50 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/common/exception/ExceptionType.java
> +    BE_NOT_AN_ADMIN("관리자만 접근할 수 있습니다.", FORBIDDEN, BeNotAnAdminException.class),
NOT_AUTHOR_EXCEPTION을  DO_NOT_HAVE_ACCESS로  바꾸고 exception 클래스 명을 DoNotHaveAccess로 바꾸는 어떨까요?

2022-05-14 20:52 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/common/exception/ExceptionType.java
> +    BE_NOT_AN_ADMIN("관리자만 접근할 수 있습니다.", FORBIDDEN, BeNotAnAdminException.class),
have와 access가 같이 사용되니까 어색하지 않나요??

2022-05-14 20:53 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/member/dto/MemberEmbeddedDto.java
> +public class MemberEmbeddedDto {
관리자 페이지 영상 리스트와 영상 상세 정보에 들어가는 member dto인데 이전에 만들어진게 없다면 MemberDto로 변경하겠습니다

2022-05-14 20:54 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/member/dto/MemberEmbeddedDto.java
> +public class MemberEmbeddedDto {
현재 관리자 페이지에서 회원 조회기능 구현중인데 클래스 이름 통일하는게 어떨까요?

2022-05-14 20:55 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/dto/AdminPageVideoListResponse.java
> +public class AdminPageVideoListResponse {
영상 목록이니깐 리스트가 들어가야하지 않을까요?

2022-05-14 20:55 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/dto/VideoListResponse.java
> +public class VideoListResponse {
위 코멘트 참고해주세요!

2022-05-14 20:55 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/dto/AdminPageVideoListResponse.java
> +public class AdminPageVideoListResponse {
반환할 때 List<AdminPageVideoListResponse> 와 같으면 의미가 중복될 것 같습니다.

2022-05-14 21:04 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/ui/VideoSearchController.java
> +public class VideoSearchController {
우테코 프로젝트에서  분리해서 만든걸 본적이 있는 것 같아 검색과 영상은 관심사가 다르다고 생각하여 분리했습니다.  그런데 찾아보니 제가 잘못 봤었네요.  통합하는게 좋을까요?

2022-05-14 21:06 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +    @GetMapping("/admin")
uri 정하는게 메서드 명 처럼 어려운 것 같네요😂 좋은 uri가 생각나시면 알려주세요!

2022-05-14 21:07 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/ui/VideoSearchController.java
> +public class VideoSearchController {
네! 같은 resource에 대한 요청이니까 통합하는게 좋을 것 같습니다.

2022-05-14 21:07 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/common/config/SecurityConfig.java
> +            .authorizeRequests()
분리한 이유는 따로 없는데 묶어도 된다는 걸 몰랐었네요! 같은 http 메서드끼리 묶는걸로 수정하겠습니다.

2022-05-14 21:35 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/member/dto/MemberEmbeddedDto.java
> +public class MemberEmbeddedDto {
네 통일하는게 맞는 것 같습니다! 그럼 Member dto로 바꿔 놓을게요

2022-05-14 21:36 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/dto/AdminPageVideoListResponse.java
> +public class AdminPageVideoListResponse {
감쌀 때를 생각못했네여 자고 일어나서 수정해놓을게요!

2022-05-14 21:36 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/member/dto/MemberEmbeddedDto.java
> +public class MemberEmbeddedDto {
`MemberInfoResponseForAdmin` 로 바꾸는건 어떤가요?!
이미 구현이 끝나가지고 ㅎㅎ..

2022-05-14 21:36 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/ui/VideoSearchController.java
> +public class VideoSearchController {
네 이것두 일어나서 수정해놓을게요🙂

2022-05-14 23:58 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +    @GetMapping("/admin")
/v1/admins/videos
/v1/admin/videos

이 정도로만 해도 될 것 같아요!

2022-05-14 23:58 UTC, jaeesu approved these changes

2022-05-15 00:03 UTC, ch0213 approved these changes

2022-05-15 00:05 UTC, ch0213 requested changes
일어나시면 커멘트 남긴 부분 확인 부탁드려요 👍

2022-05-15 04:05 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/common/exception/ExceptionType.java
> +    BE_NOT_AN_ADMIN("관리자만 접근할 수 있습니다.", FORBIDDEN, BeNotAnAdminException.class),
NoAccessPermission 은 어떤가용?

2022-05-15 04:07 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/member/dto/MemberEmbeddedDto.java
> +public class MemberEmbeddedDto {
영상 상세 정보에서도 쓰여서 ForAdmi은 빼고 `MemberInfoResponse`는 어떠신가요?

2022-05-15 04:14 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/video/ui/VideoController.java
> +    @GetMapping("/admin")
`/v1/admin/videos` 요걸루 하겠습니다!

2022-05-15 09:47 UTC, seongho-joo commented
깃 머지과정에서 문제가 발생해 새로운 브랜치에서 PR 올리겠습니다

2022-05-15 09:47 UTC, closed without merging