docs: ReadMe 작성
numbble/backend pull request #55
Opened 2022-05-14 16:50 UTC by jaeesu

###  :speech_balloon: Motivation
* 컴포넌트 아키텍처
* Erd Diagram
* 기술 스택
* 구현 기능
* api 문서

2022-05-14 16:58 UTC, ch0213 approved these changes
고생하셨습니다 👍

2022-05-14 21:38 UTC, seongho-joo approved these changes
고생하셨어요!

2022-05-14 21:40 UTC, seongho-joo requested changes

2022-05-14 21:40 UTC, seongho-joo commented on README.md
> +
기술 스택부분 아이콘 이용해서 하는건 어떨까요?

2022-05-14 23:37 UTC, ch0213 commented on README.md
> +
글로 쓰는게 한 눈에 알아보기 쉽지 않나요?

2022-05-14 23:59 UTC, jaeesu commented on README.md
> +
이미 컴포넌트 아키텍처에서 메인이 되는 건 시각적으로 보여줘서 여기서는 텍스트가 낫다고 생각합니다!

2022-05-15 05:26 UTC, seongho-joo commented on README.md
> +
아 네 알겠습니다!

2022-05-15 05:26 UTC, seongho-joo approved these changes

2022-05-15 09:54 UTC, merged