feat: 관리자 페이지에서 회원 목록 조회 및 삭제
numbble/backend pull request #57
Opened 2022-05-14 23:34 UTC by ch0213

###  :speech_balloon: Motivation
* 관리자 페이지에서 회원 목록 조회 및 삭제

### :exclamation: Key changes
* 키워드를 기반으로 회원 목록 조회 - 키워드가 이메일 또는 이름에 포함되면 검색됨
* 회원 ID로 삭제
* 관리자만 요청 가능하도록 Security 설정

###  :pencil2: To Reviewers

2022-05-14 23:59 UTC, jaeesu approved these changes

2022-05-15 10:24 UTC, seongho-joo requested changes

2022-05-15 10:24 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/member/member/infrastructure/MemberCustomRepositoryImpl.java
> +    BooleanExpression checkContainsKeyword(String keyword) {
limit를 걸어둔 List 크기를 넘겨도 토탈 페이지나 총 element 수를 알 수있나요?

2022-05-15 11:39 UTC, seongho-joo approved these changes

2022-05-15 13:03 UTC, merged