fix: 요구사항 반영
numbble/backend pull request #61
Opened 2022-05-16 16:43 UTC by seongho-joo

###  :speech_balloon: Motivation
* 무엇을 어떻게 개발했는지 설명해주세요.

### :exclamation: Key changes
* BindException Handler 추가
* 사용자별 영상 목록 테스트 추가
* `getAllVideos` where 추가
* 업로드 요청, 수정 요청 중고여부 필드 snake case로 변경
* 관리자 페이지 영상 목록 reponse 제네릭 타입 수정
* `VideoSearchRequest` lastId 필드 제거
* `searchVideoByKeyword` lastId 파라미터 추가

###  :pencil2: To Reviewers
* reviewer들에게 전하고 싶은 말이 있다면 적어주세요.

2022-05-17 14:50 UTC, jaeesu requested changes

2022-05-17 14:50 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/common/exception/GlobalExceptionController.java
> +    @ExceptionHandler(BindException.class)
따로 함수 빼지말고 위의 exceptionHadler 같이 사용하면 됩니다.

2022-05-17 15:37 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/common/exception/GlobalExceptionController.java
> +    @ExceptionHandler(BindException.class)
```java
@ExceptionHandler(value = {MethodArgumentNotValidException.class, BindException.class})
    public ResponseEntity<BaseErrorResponse> handleValidationExceptions(MethodArgumentNotValidException exception, BindException bindException) {
        Map<String, String> errors = new HashMap<>();
        exception.getBindingResult().getAllErrors()
                .forEach(error -> errors.put(((FieldError) error).getField(), error.getDefaultMessage()));
        bindException.getBindingResult().getAllErrors()
            .forEach(error -> errors.put(((FieldError) error).getField(), error.getDefaultMessage()));
        return new ResponseEntity<>(BaseErrorResponse.of(VALID_ERROR_MESSAGE, errors), BAD_REQUEST);
    }
```
이렇게 같이사용하는게 아닌가요? 이렇게 추가해서 실행을 해보니 또 아래와 같이뜨네요

<img width="398" alt="스크린샷 2022-05-18 오전 12 36 36" src="https://user-images.githubusercontent.com/45463495/168851262-3b02962a-e0ec-40cc-87ed-0314f6f262d7.png">

2022-05-18 06:45 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/common/exception/GlobalExceptionController.java
> +    @ExceptionHandler(BindException.class)
`MethodArgumentNotValidException`의 상위 클래스가 `BindException`이라서 `BindException`으로 수정했습니다.

2022-05-18 08:29 UTC, ch0213 approved these changes
고생하셨습니다 👍

2022-05-19 00:00 UTC, jaeesu approved these changes

2022-05-19 00:00 UTC, merged