feat: 기초적인 도메인 생성 (#8)
numbble/backend pull request #9
Opened 2022-04-25 07:47 UTC by ch0213

###  :speech_balloon: Motivation
* 회원, 비디오(+댓글), 좋아요 도메인 생성했습니다. 비디오, 댓글이 일대다 관계라 댓글을 일급 컬렉션으로 관리하기 위해 Comments를 생성했어요.

2022-04-25 10:38 UTC, seongho-joo approved these changes
고생하셨습니다!

2022-04-25 12:16 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/common/exception/ExceptionType.java
> +    WRONG_PASSWORD("비밀번호가 틀렸습니다.", BAD_REQUEST, WrongPasswordException.class);
이 부분 BAD_REQUEST -> UNAUTHORIZED로 수정해주세요!

2022-04-25 12:16 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Comments.java
> +    @OneToMany(cascade = ALL, orphanRemoval = true)
임베디드 타입에서는 mappedBy 지정 안 해도 되나요?

2022-04-25 12:21 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/domain/Comments.java
> +    @OneToMany(cascade = ALL, orphanRemoval = true)
일대다 단방향 관계이기 때문에 연관관계의 주인인 Video에 JoinColum만 있으면 됩니다. 
원래 일대다 단방향 관계는 잘 사용하지 않는데, 영상이랑 댓글의 생명주기가 완전히 일치한다고 생각해서 사용했습니다.

2022-04-25 12:21 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/common/exception/ExceptionType.java
> +    WRONG_PASSWORD("비밀번호가 틀렸습니다.", BAD_REQUEST, WrongPasswordException.class);
네 알겠습니다!

2022-04-25 12:21 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/domain/Comments.java
> +    @OneToMany(cascade = ALL, orphanRemoval = true)
일대다 단방향 관계이기 때문에 연관관계의 주인인 Video에 JoinColum만 있으면 됩니다.
원래 일대다 단방향 관계는 잘 사용하지 않는데, 영상이랑 댓글의 생명주기가 완전히 일치한다고 생각해서 사용했습니다.

2022-04-25 12:29 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/video/domain/Comments.java
> +    @OneToMany(cascade = ALL, orphanRemoval = true)
아! 제가 코드를 잘못 확인했었네요ㅠㅠ 이 부분은 확인했습니다! 😃
혹시 List<Comment>를 video class에 바로 넣지 않고 임베디드 타입으로 생성하신 이유를 알 수 있을까요?

2022-04-25 12:34 UTC, ch0213 commented on src/main/java/numble/team4/shortformserver/video/domain/Comments.java
> +    @OneToMany(cascade = ALL, orphanRemoval = true)
일급 컬렉션으로 관리하면 얻는 이점들이 많아서 사용했습니다! 글로 적으면 많을 것 같아 참고했던 링크 공유하겠습니다.

2022-04-25 12:48 UTC, seongho-joo requested changes
좋아요 수가 Video 엔티티에 포함돼야할 것 같은데 혹시 추가안하신 이유가 있나요?

2022-04-25 12:51 UTC, ch0213 commented
> 좋아요 수가 Video 엔티티에 포함돼야할 것 같은데 혹시 추가안하신 이유가 있나요?

Video의 viewCount로 추가했습니다!

2022-04-25 12:52 UTC, ch0213 commented
> 좋아요 수가 Video 엔티티에 포함돼야할 것 같은데 혹시 추가안하신 이유가 있나요?

아 제가 잘못 생각했네요 수정하겠습니다 ㅎㅎ

2022-04-25 23:22 UTC, jaeesu commented on src/main/java/numble/team4/shortformserver/common/exception/ExceptionType.java
> +    WRONG_PASSWORD("비밀번호가 틀렸습니다.", BAD_REQUEST, WrongPasswordException.class);
=> 401은 인가에 대한 에러 코드지만, 현재는 인증에 관한 부분이므로 BAD_REQUEST로 유지하기로 함.

2022-04-26 09:17 UTC, jaeesu commented on src/main/resources/init.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
auto_increment 사이즈를 50으로 두신 이유가 있나요?

2022-04-26 12:23 UTC, seongho-joo commented on src/main/java/numble/team4/shortformserver/common/domain/BaseTimeEntity.java
> +public class BaseTimeEntity {
modifiedAt은 수정이 돼야 바뀌는걸로 알고있습니다.

2022-04-26 12:44 UTC, seongho-joo approved these changes

2022-04-26 20:08 UTC, ch0213 commented on src/main/resources/init.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
sequence에서 allcationSize의 크기를 설정하는 것과 유사하다고 생각하여 설정했는데,
InnoDB에서는 Auto Increment를 메모리상에서 관리하는군요. 제거해도 될 것 같습니다!

2022-04-27 03:03 UTC, jaeesu approved these changes

2022-04-27 03:04 UTC, merged